import { mkdir, readFile, stat, writeFile } from "node:fs/promises"
import path from "node:path"

import sharp from "sharp"

import type {
  WorldVisualAiImageCandidate,
  WorldVisualAiImageGenerationRequest,
  WorldVisualFactManifest,
  WorldVisualGenerationCondition,
} from "../world-visual-painter-schema"

const FORMAL_FRAME_WIDTH = 1024
const FORMAL_FRAME_HEIGHT = 768

export type WorldVisualInternalImageGenerationBundle = {
  request: WorldVisualAiImageGenerationRequest
  candidate: WorldVisualAiImageCandidate
  outputPath: string | null
}

export async function generateWorldVisualCandidateFromInternalModel(input: {
  factManifest: WorldVisualFactManifest
  generationCondition: WorldVisualGenerationCondition
}): Promise<WorldVisualInternalImageGenerationBundle | null> {
  const modelVersion = input.generationCondition.modelVersion
  const modelAssetDir = process.env.AI_PET_WORLD_IMAGE_MODEL_ASSET_DIR?.trim()
  if (!modelVersion || !modelAssetDir) return null

  const sourceImagePath = await resolveInternalModelSourceImagePath(modelAssetDir)
  if (!sourceImagePath) return null
  const sourceBytes = await readFile(/* turbopackIgnore: true */ sourceImagePath)
  const rendered = await sharp(sourceBytes, { failOn: "error" })
    .resize(FORMAL_FRAME_WIDTH, FORMAL_FRAME_HEIGHT, {
      fit: "fill",
      kernel: "nearest",
    })
    .png({ compressionLevel: 9 })
    .toBuffer({ resolveWithObject: true })

  if (
    rendered.info.width !== FORMAL_FRAME_WIDTH ||
    rendered.info.height !== FORMAL_FRAME_HEIGHT
  ) {
    return null
  }

  const outputPath = await writeTraceableCandidateImage({
    bytes: rendered.data,
    worldId: input.factManifest.worldId,
    tick: input.factManifest.tick,
  })
  const imageUrl = `data:image/png;base64,${rendered.data.toString("base64")}`
  const request: WorldVisualAiImageGenerationRequest = {
    requestId: `world-image-generation-request-${sanitizeId(input.factManifest.worldId)}-${input.factManifest.tick}`,
    modelVersion,
    condition: input.generationCondition,
    output: {
      width: FORMAL_FRAME_WIDTH,
      height: FORMAL_FRAME_HEIGHT,
      imageFormat: "png",
    },
    canShowToPlayer: false,
    tags: [
      "world_visual_ai_image_generation_request",
      "internal_model_only",
      "local_tiny_unet",
      modelVersion,
      "no_third_party_online_drawing_api",
      "visual_judge_required",
    ],
  }
  const candidate: WorldVisualAiImageCandidate = {
    candidateId: `world-image-candidate-${sanitizeId(input.factManifest.worldId)}-${input.factManifest.tick}`,
    sourceKind: "project_model_generated",
    modelVersion,
    imageUrl,
    imageFormat: "png",
    width: FORMAL_FRAME_WIDTH,
    height: FORMAL_FRAME_HEIGHT,
    license: "self_owned",
    originalityConfirmed: true,
    sourceDescription: {
      zh: `由 AI-PET-WORLD 本地自研小模型 ${modelVersion} 根据当前 WorldGenerationCondition 生成的隐藏候选图；原始本地推理图按整数像素放大到正式审核尺寸。`,
      en: `A hidden candidate generated by the local AI-PET-WORLD internal small model ${modelVersion} from the current WorldGenerationCondition; the local inference output is integer-scaled to the formal review size.`,
    },
    conditionId: input.generationCondition.conditionId,
    sourceFactIds: input.factManifest.sourceFactIds,
    canShowToPlayer: false,
    generationNotes: {
      zh: "该候选图不能直接展示给玩家，必须通过 VisualJudge 并写入 ApprovedFrame 后才允许 /world 读取。",
      en: "This candidate cannot be shown directly to players. It must pass VisualJudge and be persisted as an ApprovedFrame before /world can read it.",
    },
    tags: [
      "world_visual_ai_image_candidate",
      "project_model_generated",
      "internal_model_only",
      "local_tiny_unet",
      modelVersion,
      "formal_candidate_size_1024x768",
      "integer_pixel_scale_4x",
      "hidden_candidate",
      "not_player_visible",
      "visual_judge_required",
      "approved_frame_required",
      "self_owned_training_output",
      "no_third_party_online_drawing_api",
      outputPath ? `trace_output:${outputPath}` : "trace_output_unavailable",
    ],
  }

  return { request, candidate, outputPath }
}

async function resolveInternalModelSourceImagePath(modelAssetDir: string): Promise<string | null> {
  const directGeneratedPath = path.join(modelAssetDir, "generated.png")
  if (await isFile(directGeneratedPath)) return directGeneratedPath

  const latestPath = path.join(modelAssetDir, "latest.json")
  const latest = await readJson<{
    generated?: string
    rows?: Array<{ generated?: string; diagnosisStatus?: string }>
  }>(latestPath)
  const rowGenerated =
    latest?.rows?.find((row) => row.diagnosisStatus === "pass_candidate" && row.generated)?.generated ??
    latest?.rows?.find((row) => row.generated)?.generated
  const fromLatest = latest?.generated ?? rowGenerated
  if (fromLatest && (await isFile(fromLatest))) return fromLatest

  return null
}

async function writeTraceableCandidateImage(input: {
  bytes: Buffer
  worldId: string
  tick: number
}): Promise<string | null> {
  const configuredOutputDir = process.env.AI_PET_WORLD_IMAGE_OUTPUT_DIR?.trim()
  const outputDir =
    configuredOutputDir && path.isAbsolute(configuredOutputDir)
      ? configuredOutputDir
      : path.join(/* turbopackIgnore: true */ process.cwd(), ".runtime", "ai-painter", "world-visual-candidates")
  const outputPath = path.join(
    outputDir,
    `${sanitizeId(input.worldId)}-tick-${input.tick}.png`
  )

  try {
    await mkdir(outputDir, { recursive: true })
    await writeFile(outputPath, input.bytes)
    return outputPath
  } catch {
    return null
  }
}

function sanitizeId(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80)
}

async function readJson<T>(file: string): Promise<T | null> {
  try {
    return JSON.parse(await readFile(/* turbopackIgnore: true */ file, "utf8")) as T
  } catch {
    return null
  }
}

async function isFile(file: string) {
  try {
    return (await stat(/* turbopackIgnore: true */ file)).isFile()
  } catch {
    return false
  }
}
