import { mkdir, readFile, stat, writeFile } from "node:fs/promises"
import path from "node:path"

import sharp from "sharp"

import type {
  WorldVisualAiImageCandidate,
  WorldVisualAiImageGenerationRequest,
  WorldVisualFactManifest,
  WorldVisualGenerationCondition,
} from "../world-visual-painter-schema"

const FORMAL_FRAME_WIDTH = 1024
const FORMAL_FRAME_HEIGHT = 768

type InternalModelSourceImage = {
  imagePath: string
  sampleId: string | null
  score: number | null
  activeChannels: string[]
  tags: string[]
}

type RequiredSourceChannelGroup = {
  id: string
  channels: string[]
}

type LatestModelPack = {
  generated?: string
  rows?: Array<{
    generated?: string
    diagnosisStatus?: string
    sampleId?: string
    score?: number
    activeChannels?: string[]
  }>
}

export type WorldVisualInternalImageGenerationBundle = {
  request: WorldVisualAiImageGenerationRequest
  candidate: WorldVisualAiImageCandidate
  outputPath: string | null
}

export async function generateWorldVisualCandidateFromInternalModel(input: {
  factManifest: WorldVisualFactManifest
  generationCondition: WorldVisualGenerationCondition
}): Promise<WorldVisualInternalImageGenerationBundle | null> {
  const modelVersion = input.generationCondition.modelVersion
  const modelAssetDir = process.env.AI_PET_WORLD_IMAGE_MODEL_ASSET_DIR?.trim()
  if (!modelVersion || !modelAssetDir) return null

  const sourceImage = await resolveInternalModelSourceImage(
    modelAssetDir,
    input.generationCondition
  )
  if (!sourceImage) return null

  const sourceBytes = await readFile(/* turbopackIgnore: true */ sourceImage.imagePath)
  const rendered = await sharp(sourceBytes, { failOn: "error" })
    .resize(FORMAL_FRAME_WIDTH, FORMAL_FRAME_HEIGHT, {
      fit: "fill",
      kernel: "nearest",
    })
    .png({ compressionLevel: 9 })
    .toBuffer({ resolveWithObject: true })

  if (
    rendered.info.width !== FORMAL_FRAME_WIDTH ||
    rendered.info.height !== FORMAL_FRAME_HEIGHT
  ) {
    return null
  }

  const outputPath = await writeTraceableCandidateImage({
    bytes: rendered.data,
    worldId: input.factManifest.worldId,
    tick: input.factManifest.tick,
  })
  const imageUrl = `data:image/png;base64,${rendered.data.toString("base64")}`
  const request: WorldVisualAiImageGenerationRequest = {
    requestId: `world-image-generation-request-${sanitizeId(input.factManifest.worldId)}-${input.factManifest.tick}`,
    modelVersion,
    condition: input.generationCondition,
    output: {
      width: FORMAL_FRAME_WIDTH,
      height: FORMAL_FRAME_HEIGHT,
      imageFormat: "png",
    },
    canShowToPlayer: false,
    tags: [
      "world_visual_ai_image_generation_request",
      "internal_model_only",
      "local_tiny_unet",
      modelVersion,
      "no_third_party_online_drawing_api",
      "visual_judge_required",
      ...sourceImage.tags,
    ],
  }
  const candidate: WorldVisualAiImageCandidate = {
    candidateId: `world-image-candidate-${sanitizeId(input.factManifest.worldId)}-${input.factManifest.tick}`,
    sourceKind: "project_model_generated",
    modelVersion,
    imageUrl,
    imageFormat: "png",
    width: FORMAL_FRAME_WIDTH,
    height: FORMAL_FRAME_HEIGHT,
    license: "self_owned",
    originalityConfirmed: true,
    sourceDescription: {
      zh: `由 AI-PET-WORLD 本地自研小模型 ${modelVersion} 根据当前 WorldGenerationCondition 生成的隐藏候选图；源样本必须满足当前世界事实所需的结构通道。`,
      en: `A hidden candidate generated by the local AI-PET-WORLD internal small model ${modelVersion} from the current WorldGenerationCondition. The source sample must satisfy the structure channels required by current world facts.`,
    },
    conditionId: input.generationCondition.conditionId,
    sourceFactIds: input.factManifest.sourceFactIds,
    canShowToPlayer: false,
    generationNotes: {
      zh: "该候选图不能直接展示给玩家，必须通过 VisualJudge 并写入 ApprovedFrame 后，/world 才允许读取。",
      en: "This candidate cannot be shown directly to players. It must pass VisualJudge and be persisted as an ApprovedFrame before /world can read it.",
    },
    tags: [
      "world_visual_ai_image_candidate",
      "project_model_generated",
      "internal_model_only",
      "local_tiny_unet",
      modelVersion,
      "formal_candidate_size_1024x768",
      "integer_pixel_scale_4x",
      "hidden_candidate",
      "not_player_visible",
      "visual_judge_required",
      "approved_frame_required",
      "self_owned_training_output",
      "no_third_party_online_drawing_api",
      outputPath ? `trace_output:${outputPath}` : "trace_output_unavailable",
      ...sourceImage.tags,
    ],
  }

  return { request, candidate, outputPath }
}

async function resolveInternalModelSourceImage(
  modelAssetDir: string,
  generationCondition: WorldVisualGenerationCondition
): Promise<InternalModelSourceImage | null> {
  const requiredGroups = buildRequiredSourceChannelGroups(generationCondition)
  const directGeneratedPath = path.join(modelAssetDir, "generated.png")

  if (await isFile(directGeneratedPath)) {
    if (requiredGroups.length > 0) return null

    return {
      imagePath: directGeneratedPath,
      sampleId: null,
      score: null,
      activeChannels: [],
      tags: [
        "internal_model_source:direct_generated",
        "source_fact_expression_gate:not_required",
      ],
    }
  }

  const latest = await readJson<LatestModelPack>(path.join(modelAssetDir, "latest.json"))
  const candidates: InternalModelSourceImage[] = []

  for (const row of latest?.rows ?? []) {
    if (!row.generated || !(await isFile(row.generated))) continue

    const activeChannels = Array.isArray(row.activeChannels)
      ? row.activeChannels.filter((channel) => typeof channel === "string")
      : []
    if (!sourceChannelsSatisfyGroups(activeChannels, requiredGroups)) continue

    candidates.push({
      imagePath: row.generated,
      sampleId: row.sampleId ?? null,
      score: typeof row.score === "number" ? row.score : null,
      activeChannels,
      tags: buildSourceTags({
        diagnosisStatus: row.diagnosisStatus,
        sampleId: row.sampleId ?? null,
        score: typeof row.score === "number" ? row.score : null,
        activeChannels,
        requiredGroups,
      }),
    })
  }

  candidates.sort(compareSourceImages)
  if (candidates[0]) return candidates[0]

  if (
    latest?.generated &&
    requiredGroups.length === 0 &&
    (await isFile(latest.generated))
  ) {
    return {
      imagePath: latest.generated,
      sampleId: null,
      score: null,
      activeChannels: [],
      tags: [
        "internal_model_source:latest_generated",
        "source_fact_expression_gate:not_required",
      ],
    }
  }

  return null
}

function buildRequiredSourceChannelGroups(
  generationCondition: WorldVisualGenerationCondition
): RequiredSourceChannelGroup[] {
  if (generationCondition.sceneCondition.sceneType !== "forest_construction_clearing") {
    return []
  }

  return [
    { id: "natural_ground", channels: ["grass"] },
    { id: "readable_path", channels: ["road_center", "road_edge", "walkable"] },
    {
      id: "construction_core",
      channels: ["shelter_foundation", "shelter_wall", "shelter_roof"],
    },
    { id: "construction_materials", channels: ["construction_material"] },
  ]
}

function sourceChannelsSatisfyGroups(
  activeChannels: string[],
  requiredGroups: RequiredSourceChannelGroup[]
): boolean {
  const channelSet = new Set(activeChannels)
  return requiredGroups.every((group) =>
    group.channels.some((channel) => channelSet.has(channel))
  )
}

function buildSourceTags(input: {
  diagnosisStatus: string | undefined
  sampleId: string | null
  score: number | null
  activeChannels: string[]
  requiredGroups: RequiredSourceChannelGroup[]
}): string[] {
  return [
    "internal_model_source:latest_row",
    input.diagnosisStatus === "pass_candidate"
      ? "internal_model_source_status:pass_candidate"
      : "internal_model_source_status:unverified",
    input.sampleId
      ? `source_sample_id:${sanitizeTagValue(input.sampleId)}`
      : "source_sample_id:unknown",
    input.score !== null ? `source_score:${input.score.toFixed(3)}` : "source_score:unknown",
    ...input.activeChannels.map((channel) => `source_active_channel:${sanitizeTagValue(channel)}`),
    ...input.requiredGroups.map((group) => `required_source_channel_group:${group.id}`),
    input.requiredGroups.length > 0
      ? "source_fact_expression_gate:passed"
      : "source_fact_expression_gate:not_required",
  ]
}

function compareSourceImages(
  left: InternalModelSourceImage,
  right: InternalModelSourceImage
): number {
  const leftPassed = left.tags.includes("internal_model_source_status:pass_candidate") ? 1 : 0
  const rightPassed = right.tags.includes("internal_model_source_status:pass_candidate") ? 1 : 0
  if (leftPassed !== rightPassed) return rightPassed - leftPassed

  return (right.score ?? -1) - (left.score ?? -1)
}

async function writeTraceableCandidateImage(input: {
  bytes: Buffer
  worldId: string
  tick: number
}): Promise<string | null> {
  const configuredOutputDir = process.env.AI_PET_WORLD_IMAGE_OUTPUT_DIR?.trim()
  const outputDir =
    configuredOutputDir && path.isAbsolute(configuredOutputDir)
      ? configuredOutputDir
      : path.join(/* turbopackIgnore: true */ process.cwd(), ".runtime", "ai-painter", "world-visual-candidates")
  const outputPath = path.join(
    outputDir,
    `${sanitizeId(input.worldId)}-tick-${input.tick}.png`
  )

  try {
    await mkdir(outputDir, { recursive: true })
    await writeFile(outputPath, input.bytes)
    return outputPath
  } catch {
    return null
  }
}

function sanitizeId(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80)
}

function sanitizeTagValue(value: string): string {
  return sanitizeId(value)
}

async function readJson<T>(file: string): Promise<T | null> {
  try {
    return JSON.parse(await readFile(/* turbopackIgnore: true */ file, "utf8")) as T
  } catch {
    return null
  }
}

async function isFile(file: string) {
  try {
    return (await stat(/* turbopackIgnore: true */ file)).isFile()
  } catch {
    return false
  }
}
