/**
 * 当前文件负责：提供 MVP 阶段的紫微视觉基准类型。
 */

import type {
  VisualDNA,
  ZiweiVisualArchetype,
} from "./visual-dna.types"

export const ziweiVisualProfiles: Record<ZiweiVisualArchetype, VisualDNA> = {
  structured_builder: {
    archetype: "structured_builder",
    colorTone: "metal_clear",
    butlerSilhouette: "steady_compact",
    petMatchType: "stable_attached",
    homeStyle: "orderly_structured",
    gardenStyle: "neat_low_grass",
    shelterStyle: "straight_frame",
    carePriority: "storage_first",
    orderVsNature: 88,
    warmthVsDistance: 52,
    protectionNeed: 58,
    decorationNeed: 28,
    confidence: 84,
    source: "mock",
  },
  warm_caretaker: {
    archetype: "warm_caretaker",
    colorTone: "earth_warm",
    butlerSilhouette: "soft_round",
    petMatchType: "soft_companion",
    homeStyle: "warm_care_first",
    gardenStyle: "warm_flower_patch",
    shelterStyle: "soft_canopy",
    carePriority: "comfort_first",
    orderVsNature: 46,
    warmthVsDistance: 88,
    protectionNeed: 48,
    decorationNeed: 56,
    confidence: 86,
    source: "mock",
  },
  protective_keeper: {
    archetype: "protective_keeper",
    colorTone: "wood_green",
    butlerSilhouette: "guarded_upright",
    petMatchType: "alert_guardian",
    homeStyle: "protected_boundary",
    gardenStyle: "protected_shrub_edge",
    shelterStyle: "reinforced_edge",
    carePriority: "safety_first",
    orderVsNature: 68,
    warmthVsDistance: 58,
    protectionNeed: 92,
    decorationNeed: 34,
    confidence: 85,
    source: "mock",
  },
  aesthetic_organizer: {
    archetype: "aesthetic_organizer",
    colorTone: "fire_bright",
    butlerSilhouette: "elegant_light",
    petMatchType: "curious_playful",
    homeStyle: "flowered_aesthetic",
    gardenStyle: "decorative_garden",
    shelterStyle: "decorated_roof",
    carePriority: "beauty_first",
    orderVsNature: 54,
    warmthVsDistance: 72,
    protectionNeed: 42,
    decorationNeed: 94,
    confidence: 83,
    source: "mock",
  },
  quiet_maintainer: {
    archetype: "quiet_maintainer",
    colorTone: "water_quiet",
    butlerSilhouette: "quiet_simple",
    petMatchType: "quiet_observer",
    homeStyle: "quiet_minimal",
    gardenStyle: "quiet_shade",
    shelterStyle: "low_quiet_shelter",
    carePriority: "stability_first",
    orderVsNature: 62,
    warmthVsDistance: 38,
    protectionNeed: 56,
    decorationNeed: 22,
    confidence: 82,
    source: "mock",
  },
  adaptive_planner: {
    archetype: "adaptive_planner",
    colorTone: "moon_soft",
    butlerSilhouette: "balanced_adaptive",
    petMatchType: "adaptive_partner",
    homeStyle: "adaptive_mixed",
    gardenStyle: "mixed_natural",
    shelterStyle: "adaptive_shelter",
    carePriority: "context_first",
    orderVsNature: 66,
    warmthVsDistance: 66,
    protectionNeed: 64,
    decorationNeed: 60,
    confidence: 80,
    source: "mock",
  },
}
