/**
 * 当前文件负责：注册像素资产拆分层的低保真部件定义。
 */

import type { PixelAssetPartDefinition } from "./pixel-asset-part-schema"

function definePart(input: Omit<PixelAssetPartDefinition, "id" | "renderMode" | "defaultVisible" | "anchor"> & {
  renderMode?: PixelAssetPartDefinition["renderMode"]
  defaultVisible?: boolean
  anchor?: PixelAssetPartDefinition["anchor"]
}): PixelAssetPartDefinition {
  return {
    id: `pixel-asset-part-${input.kind}`,
    renderMode: input.renderMode ?? "graphics_placeholder",
    defaultVisible: input.defaultVisible ?? true,
    anchor: input.anchor ?? { x: 0.5, y: 0.5 },
    ...input,
  }
}

export const PIXEL_ASSET_PARTS: PixelAssetPartDefinition[] = [
  definePart({
    kind: "grass_tile_base",
    category: "ground",
    targetWorldObjects: ["grass_base", "home_land"],
    layer: "groundBaseLayer",
    usage: "tile",
    displayName: "基础草地图块",
    description: "低保真阶段用于铺设家园土地的基础草地图块。",
    size: { width: 16, height: 16 },
    styleTags: ["home", "garden", "quiet"],
    stateTags: ["base", "repeatable"],
    canRepeat: true,
  }),
  definePart({
    kind: "grass_detail_dot",
    category: "ground",
    targetWorldObjects: ["grass_detail"],
    layer: "groundDetailLayer",
    usage: "tile",
    displayName: "草地细节点",
    description: "打破地表重复感的轻量草地细节。",
    size: { width: 4, height: 4 },
    styleTags: ["garden", "aesthetic", "adaptive"],
    stateTags: ["detail"],
    canRepeat: true,
  }),
  definePart({
    kind: "flower_pixel_cluster",
    category: "environment",
    targetWorldObjects: ["grass_flower", "garden_patch"],
    layer: "groundDetailLayer",
    usage: "object_part",
    displayName: "小花像素簇",
    description: "用于表现舒适、审美和庭院倾向的小花部件。",
    size: { width: 8, height: 8 },
    styleTags: ["garden", "aesthetic", "comfort"],
    stateTags: ["garden", "decorative"],
    canRepeat: true,
  }),
  definePart({
    kind: "weed_pixel_cluster",
    category: "environment",
    targetWorldObjects: ["grass_weed"],
    layer: "groundDetailLayer",
    usage: "object_part",
    displayName: "杂草像素簇",
    description: "用于表达自然扩张、维护需求和家园状态变化。",
    size: { width: 8, height: 8 },
    styleTags: ["garden", "adaptive", "order"],
    stateTags: ["maintenance_needed"],
    canRepeat: true,
  }),
  definePart({
    kind: "dirt_path_tile",
    category: "path",
    targetWorldObjects: ["dirt_path", "home_path", "town_path"],
    layer: "pathLayer",
    usage: "tile",
    displayName: "泥土路径图块",
    description: "早期家园和小镇路线的基础路径部件。",
    size: { width: 16, height: 16 },
    styleTags: ["home", "town", "order"],
    stateTags: ["path", "early"],
    canRepeat: true,
  }),
  definePart({
    kind: "stone_path_tile",
    category: "path",
    targetWorldObjects: ["stone_path", "home_path", "town_path"],
    layer: "pathLayer",
    usage: "tile",
    displayName: "石板路径图块",
    description: "结构型和秩序型家园更容易使用的稳定路径部件。",
    size: { width: 16, height: 16 },
    styleTags: ["structured", "stability", "order"],
    stateTags: ["path", "stable"],
    canRepeat: true,
  }),
  definePart({
    kind: "shelter_floor_base",
    category: "home_structure",
    targetWorldObjects: ["temporary_shelter", "home_foundation"],
    layer: "structureBaseLayer",
    usage: "object_part",
    displayName: "住所地面底座",
    description: "临时住所和后续房屋结构的底座部件。",
    size: { width: 64, height: 40 },
    styleTags: ["home", "stability", "structured"],
    stateTags: ["shelter", "base"],
    canRepeat: false,
  }),
  definePart({
    kind: "wall_panel",
    category: "home_structure",
    targetWorldObjects: ["home_wall", "temporary_shelter"],
    layer: "structureLayer",
    usage: "object_part",
    displayName: "墙体面板",
    description: "房屋主体墙面的可替换部件。",
    size: { width: 56, height: 32 },
    styleTags: ["home", "protective", "structured"],
    stateTags: ["wall"],
    canRepeat: false,
  }),
  definePart({
    kind: "roof_cap",
    category: "home_structure",
    targetWorldObjects: ["home_roof", "temporary_shelter"],
    layer: "structureDetailLayer",
    usage: "object_part",
    displayName: "屋顶部件",
    description: "表达遮蔽感、稳定感和家园完成度的屋顶部件。",
    size: { width: 72, height: 28 },
    styleTags: ["home", "protective", "stability"],
    stateTags: ["roof"],
    canRepeat: false,
  }),
  definePart({
    kind: "door_panel",
    category: "home_structure",
    targetWorldObjects: ["home_door"],
    layer: "structureDetailLayer",
    usage: "object_part",
    displayName: "门部件",
    description: "室内外切换和家园入口感的门部件。",
    size: { width: 14, height: 22 },
    styleTags: ["home", "warm", "structured"],
    stateTags: ["entrance"],
    canRepeat: false,
  }),
  definePart({
    kind: "window_panel",
    category: "home_structure",
    targetWorldObjects: ["home_window"],
    layer: "structureDetailLayer",
    usage: "object_part",
    displayName: "窗部件",
    description: "表达光线、温暖感和家园内外连通的窗部件。",
    size: { width: 12, height: 12 },
    styleTags: ["home", "warm", "aesthetic"],
    stateTags: ["window"],
    canRepeat: true,
  }),
  definePart({
    kind: "fence_segment",
    category: "home_structure",
    targetWorldObjects: ["home_fence", "home_boundary"],
    layer: "structureLayer",
    usage: "object_part",
    displayName: "围栏段",
    description: "保护型和边界型家园更早出现的围栏部件。",
    size: { width: 16, height: 12 },
    styleTags: ["boundary", "protective", "order"],
    stateTags: ["boundary"],
    canRepeat: true,
  }),
  definePart({
    kind: "garden_soil_patch",
    category: "home_facility",
    targetWorldObjects: ["garden_patch"],
    layer: "structureBaseLayer",
    usage: "object_part",
    displayName: "庭院土地区块",
    description: "庭院、花草和观察活动的基础部件。",
    size: { width: 48, height: 32 },
    styleTags: ["garden", "comfort", "aesthetic"],
    stateTags: ["garden"],
    canRepeat: true,
  }),
  definePart({
    kind: "food_bowl",
    category: "home_facility",
    targetWorldObjects: ["food_corner"],
    layer: "structureDetailLayer",
    usage: "object_part",
    displayName: "食物碗",
    description: "宠物进食和管家照护行为的低保真设施部件。",
    size: { width: 12, height: 8 },
    styleTags: ["care", "comfort", "pet_life"],
    stateTags: ["food"],
    canRepeat: false,
  }),
  definePart({
    kind: "water_bowl",
    category: "home_facility",
    targetWorldObjects: ["water_corner"],
    layer: "structureDetailLayer",
    usage: "object_part",
    displayName: "饮水碗",
    description: "宠物饮水和稳定照护节奏的低保真设施部件。",
    size: { width: 12, height: 8 },
    styleTags: ["care", "stability", "pet_life"],
    stateTags: ["water"],
    canRepeat: false,
  }),
  definePart({
    kind: "pet_bed_mat",
    category: "home_facility",
    targetWorldObjects: ["pet_bed"],
    layer: "structureDetailLayer",
    usage: "object_part",
    displayName: "宠物休息垫",
    description: "温和照护型家园优先出现的宠物休息部件。",
    size: { width: 28, height: 18 },
    styleTags: ["warm", "comfort", "pet_life"],
    stateTags: ["rest"],
    canRepeat: false,
  }),
  definePart({
    kind: "adoption_center_wall",
    category: "adoption_center",
    targetWorldObjects: ["adoption_center"],
    layer: "structureLayer",
    usage: "object_part",
    displayName: "领养中心墙体",
    description: "小镇宠物领养中心的低保真建筑主体部件。",
    size: { width: 80, height: 48 },
    styleTags: ["town", "care", "structured"],
    stateTags: ["town_service"],
    canRepeat: false,
  }),
  definePart({
    kind: "adoption_center_sign",
    category: "adoption_center",
    targetWorldObjects: ["adoption_sign"],
    layer: "structureDetailLayer",
    usage: "object_part",
    displayName: "领养中心招牌",
    description: "标记宠物领养中心入口和服务性质的部件。",
    size: { width: 36, height: 12 },
    styleTags: ["town", "arrival", "warm"],
    stateTags: ["sign"],
    canRepeat: false,
  }),
  definePart({
    kind: "adoption_counter_body",
    category: "adoption_center",
    targetWorldObjects: ["adoption_counter"],
    layer: "structureLayer",
    usage: "object_part",
    displayName: "领养登记柜台",
    description: "管家报名领养时会聚焦的服务柜台部件。",
    size: { width: 44, height: 18 },
    styleTags: ["town", "structured", "care"],
    stateTags: ["registration"],
    canRepeat: false,
  }),
  definePart({
    kind: "pet_arrival_pad",
    category: "adoption_center",
    targetWorldObjects: ["pet_arrival_point", "home_welcome_area"],
    layer: "interactionLayer",
    usage: "marker",
    displayName: "宠物抵达标记",
    description: "宠物送达家园时的关系建立点标记。",
    size: { width: 24, height: 16 },
    styleTags: ["arrival", "care", "warm", "pet_life"],
    stateTags: ["arrival"],
    canRepeat: false,
  }),
  definePart({
    kind: "butler_body_base",
    category: "butler",
    targetWorldObjects: ["butler_actor"],
    layer: "actorPartLayer",
    usage: "actor_part",
    displayName: "管家身体基础",
    description: "管家角色的低保真身体基础部件。",
    size: { width: 14, height: 22 },
    styleTags: ["structured", "care", "protective"],
    stateTags: ["actor", "body"],
    canRepeat: false,
  }),
  definePart({
    kind: "butler_tool_hammer",
    category: "butler",
    targetWorldObjects: ["butler_tool"],
    layer: "actorPartLayer",
    usage: "actor_part",
    displayName: "管家小锤子",
    description: "管家建设和维护家园时的工具部件。",
    size: { width: 8, height: 8 },
    styleTags: ["structured", "order", "stability"],
    stateTags: ["tool", "build"],
    canRepeat: false,
  }),
  definePart({
    kind: "butler_tool_clipboard",
    category: "butler",
    targetWorldObjects: ["butler_tool"],
    layer: "actorPartLayer",
    usage: "actor_part",
    displayName: "管家记录板",
    description: "管家报名领养、规划建设和观察状态时的工具部件。",
    size: { width: 8, height: 10 },
    styleTags: ["structured", "town", "order"],
    stateTags: ["tool", "record"],
    canRepeat: false,
  }),
  definePart({
    kind: "pet_body_round",
    category: "pet",
    targetWorldObjects: ["pet_actor"],
    layer: "actorPartLayer",
    usage: "actor_part",
    displayName: "圆形宠物身体",
    description: "宠物低保真阶段的圆形身体基础部件。",
    size: { width: 18, height: 14 },
    styleTags: ["pet_life", "warm", "adaptive"],
    stateTags: ["actor", "body"],
    canRepeat: false,
  }),
  definePart({
    kind: "pet_ear_round",
    category: "pet",
    targetWorldObjects: ["pet_actor"],
    layer: "actorPartLayer",
    usage: "actor_part",
    displayName: "圆耳部件",
    description: "用于组合宠物头部差异的低保真耳朵部件。",
    size: { width: 5, height: 5 },
    styleTags: ["pet_life", "warm"],
    stateTags: ["ear"],
    canRepeat: true,
  }),
  definePart({
    kind: "pet_tail_curled",
    category: "pet",
    targetWorldObjects: ["pet_actor"],
    layer: "actorPartLayer",
    usage: "actor_part",
    displayName: "卷尾部件",
    description: "表达宠物活力和情绪状态的尾巴部件。",
    size: { width: 8, height: 8 },
    styleTags: ["pet_life", "adaptive"],
    stateTags: ["tail"],
    canRepeat: false,
  }),
  definePart({
    kind: "emotion_sparkle",
    category: "effect",
    targetWorldObjects: ["pet_emotion_effect", "butler_emotion_effect"],
    layer: "actorEffectLayer",
    usage: "effect_part",
    displayName: "情绪光点",
    description: "表达好奇、温暖、轻微兴奋等情绪状态的像素效果。",
    size: { width: 6, height: 6 },
    styleTags: ["warm", "aesthetic", "pet_life"],
    stateTags: ["emotion"],
    canRepeat: true,
  }),
  definePart({
    kind: "click_ripple",
    category: "interaction",
    targetWorldObjects: ["home_door", "garden_patch", "pet_arrival_point", "home_welcome_area"],
    layer: "interactionLayer",
    usage: "effect_part",
    displayName: "点击涟漪",
    description: "玩家点击可交互点时出现的短暂反馈部件。",
    size: { width: 24, height: 24 },
    styleTags: ["arrival", "home", "warm"],
    stateTags: ["click_feedback"],
    canRepeat: true,
  }),
  definePart({
    kind: "ambient_light_overlay",
    category: "environment",
    targetWorldObjects: ["ambient_light"],
    layer: "atmosphereLayer",
    usage: "overlay",
    displayName: "环境光叠层",
    description: "表达时间、气氛和命理风格影响的低保真环境叠层。",
    size: { width: 320, height: 220 },
    styleTags: ["quiet", "warm", "aesthetic"],
    stateTags: ["atmosphere"],
    canRepeat: false,
  }),
]
