/**
 * 当前文件负责：注册像素世界的部件组合规则。
 */

import type {
  PixelCompositionPartSlot,
  PixelCompositionRule,
} from "./pixel-composition-schema"

function slot(input: PixelCompositionPartSlot): PixelCompositionPartSlot {
  return input
}

function defineRule(input: Omit<PixelCompositionRule, "id">): PixelCompositionRule {
  return {
    id: `pixel-composition-${input.kind}`,
    ...input,
  }
}

export const PIXEL_COMPOSITION_RULES: PixelCompositionRule[] = [
  defineRule({
    kind: "world_ground",
    target: "environment",
    displayName: "基础地面组合",
    description: "用基础草地、草地细节、路径和环境痕迹组合出可变化的家园地表。",
    targetWorldObjects: [
      "home_land",
      "grass_base",
      "grass_detail",
      "grass_flower",
      "grass_weed",
      "dirt_path",
      "stone_path",
      "footprint_pet",
      "maintenance_mark",
    ],
    partSlots: [
      slot({ partKind: "grass_tile_base", layer: "groundBaseLayer", order: 10, repeatHint: 80, isRequired: true, offsetX: 0, offsetY: 0 }),
      slot({ partKind: "grass_detail_dot", layer: "groundDetailLayer", order: 20, repeatHint: 28, isRequired: false, offsetX: 0, offsetY: 0 }),
      slot({ partKind: "flower_pixel_cluster", layer: "groundDetailLayer", order: 30, repeatHint: 8, isRequired: false, offsetX: 0, offsetY: 0 }),
      slot({ partKind: "weed_pixel_cluster", layer: "groundDetailLayer", order: 40, repeatHint: 8, isRequired: false, offsetX: 0, offsetY: 0 }),
      slot({ partKind: "dirt_path_tile", layer: "pathLayer", order: 50, repeatHint: 16, isRequired: false, offsetX: 0, offsetY: 0 }),
      slot({ partKind: "stone_path_tile", layer: "pathLayer", order: 60, repeatHint: 12, isRequired: false, offsetX: 0, offsetY: 0 }),
    ],
    styleTags: ["home", "garden", "adaptive", "aesthetic", "order"],
    stateTags: ["ground", "repeatable", "world_base"],
    unlockStageTags: ["ground_base"],
    defaultEnabled: true,
  }),
  defineRule({
    kind: "home_shelter",
    target: "home",
    displayName: "家园住所组合",
    description: "用底座、墙体、屋顶、门窗和围栏组合出可扩展的早期家园住所。",
    targetWorldObjects: [
      "temporary_shelter",
      "home_foundation",
      "home_wall",
      "home_roof",
      "home_door",
      "home_window",
      "home_fence",
    ],
    partSlots: [
      slot({ partKind: "shelter_floor_base", layer: "structureBaseLayer", order: 10, repeatHint: 1, isRequired: true, offsetX: 0, offsetY: 12 }),
      slot({ partKind: "wall_panel", layer: "structureLayer", order: 20, repeatHint: 1, isRequired: true, offsetX: 0, offsetY: -2 }),
      slot({ partKind: "roof_cap", layer: "structureDetailLayer", order: 30, repeatHint: 1, isRequired: false, offsetX: 0, offsetY: -24 }),
      slot({ partKind: "door_panel", layer: "structureDetailLayer", order: 40, repeatHint: 1, isRequired: true, offsetX: 0, offsetY: 10 }),
      slot({ partKind: "window_panel", layer: "structureDetailLayer", order: 50, repeatHint: 2, isRequired: false, offsetX: 18, offsetY: 0 }),
      slot({ partKind: "fence_segment", layer: "structureLayer", order: 60, repeatHint: 6, isRequired: false, offsetX: 0, offsetY: 34 }),
    ],
    styleTags: ["home", "structured", "warm", "protective", "stability"],
    stateTags: ["home", "shelter", "structure"],
    unlockStageTags: ["temporary_shelter", "foundation", "frame", "roof"],
    defaultEnabled: true,
  }),
  defineRule({
    kind: "home_care_corner",
    target: "home",
    displayName: "宠物照护角组合",
    description: "用食物碗、饮水碗和休息垫组合出宠物抵达后的基础生活区域。",
    targetWorldObjects: ["food_corner", "water_corner", "pet_bed"],
    partSlots: [
      slot({ partKind: "food_bowl", layer: "structureDetailLayer", order: 10, repeatHint: 1, isRequired: true, offsetX: -18, offsetY: 0 }),
      slot({ partKind: "water_bowl", layer: "structureDetailLayer", order: 20, repeatHint: 1, isRequired: true, offsetX: 0, offsetY: 0 }),
      slot({ partKind: "pet_bed_mat", layer: "structureDetailLayer", order: 30, repeatHint: 1, isRequired: false, offsetX: 22, offsetY: 0 }),
    ],
    styleTags: ["care", "comfort", "warm", "pet_life"],
    stateTags: ["facility", "pet_care", "basic_living"],
    unlockStageTags: ["basic_living", "pet_arrival"],
    defaultEnabled: true,
  }),
  defineRule({
    kind: "home_garden",
    target: "home",
    displayName: "庭院组合",
    description: "用庭院土地区块、小花、草地细节和围栏组合出花园与观察区域。",
    targetWorldObjects: ["garden_patch", "grass_flower", "observation_spot", "home_fence"],
    partSlots: [
      slot({ partKind: "garden_soil_patch", layer: "structureBaseLayer", order: 10, repeatHint: 2, isRequired: true, offsetX: 0, offsetY: 0 }),
      slot({ partKind: "flower_pixel_cluster", layer: "groundDetailLayer", order: 20, repeatHint: 10, isRequired: false, offsetX: 0, offsetY: 0 }),
      slot({ partKind: "fence_segment", layer: "structureLayer", order: 30, repeatHint: 5, isRequired: false, offsetX: 0, offsetY: 16 }),
    ],
    styleTags: ["garden", "aesthetic", "comfort", "adaptive"],
    stateTags: ["garden", "observe", "activity"],
    unlockStageTags: ["garden"],
    defaultEnabled: false,
  }),
  defineRule({
    kind: "town_adoption_center",
    target: "adoption_center",
    displayName: "小镇领养中心组合",
    description: "用领养中心建筑、招牌、登记柜台和抵达标记组合小镇领养服务点。",
    targetWorldObjects: [
      "adoption_center",
      "adoption_sign",
      "adoption_counter",
      "adoption_waiting_area",
      "adoption_notice_board",
      "pet_arrival_point",
    ],
    partSlots: [
      slot({ partKind: "adoption_center_wall", layer: "structureLayer", order: 10, repeatHint: 1, isRequired: true, offsetX: 0, offsetY: 0 }),
      slot({ partKind: "adoption_center_sign", layer: "structureDetailLayer", order: 20, repeatHint: 1, isRequired: true, offsetX: 0, offsetY: -28 }),
      slot({ partKind: "adoption_counter_body", layer: "structureLayer", order: 30, repeatHint: 1, isRequired: false, offsetX: 0, offsetY: 18 }),
      slot({ partKind: "pet_arrival_pad", layer: "interactionLayer", order: 40, repeatHint: 1, isRequired: false, offsetX: 42, offsetY: 24 }),
    ],
    styleTags: ["town", "arrival", "care", "structured"],
    stateTags: ["town_service", "adoption", "arrival"],
    unlockStageTags: ["town_adoption_center"],
    defaultEnabled: false,
  }),
  defineRule({
    kind: "arrival_area",
    target: "interaction",
    displayName: "宠物抵达区域组合",
    description: "用抵达标记、欢迎区和点击反馈组合宠物进入家园的关系建立点。",
    targetWorldObjects: ["pet_arrival_point", "home_welcome_area"],
    partSlots: [
      slot({ partKind: "pet_arrival_pad", layer: "interactionLayer", order: 10, repeatHint: 1, isRequired: true, offsetX: 0, offsetY: 0 }),
      slot({ partKind: "click_ripple", layer: "interactionLayer", order: 20, repeatHint: 1, isRequired: false, offsetX: 0, offsetY: 0 }),
    ],
    styleTags: ["arrival", "warm", "care", "pet_life"],
    stateTags: ["arrival", "welcome", "interaction"],
    unlockStageTags: ["pet_arrival"],
    defaultEnabled: true,
  }),
  defineRule({
    kind: "butler_actor",
    target: "butler",
    displayName: "管家角色组合",
    description: "用身体、工具和状态效果组合管家的低保真像素角色。",
    targetWorldObjects: ["butler_actor", "butler_tool", "butler_emotion_effect"],
    partSlots: [
      slot({ partKind: "butler_body_base", layer: "actorPartLayer", order: 10, repeatHint: 1, isRequired: true, offsetX: 0, offsetY: 0 }),
      slot({ partKind: "butler_tool_clipboard", layer: "actorPartLayer", order: 20, repeatHint: 1, isRequired: false, offsetX: 9, offsetY: 2 }),
      slot({ partKind: "butler_tool_hammer", layer: "actorPartLayer", order: 30, repeatHint: 1, isRequired: false, offsetX: 9, offsetY: 6 }),
      slot({ partKind: "emotion_sparkle", layer: "actorEffectLayer", order: 40, repeatHint: 2, isRequired: false, offsetX: 0, offsetY: -16 }),
    ],
    styleTags: ["structured", "care", "protective", "order"],
    stateTags: ["actor", "butler", "tool"],
    unlockStageTags: ["actor_butler"],
    defaultEnabled: true,
  }),
  defineRule({
    kind: "pet_actor",
    target: "pet",
    displayName: "宠物角色组合",
    description: "用身体、耳朵、尾巴和情绪效果组合宠物低保真角色。",
    targetWorldObjects: ["pet_actor", "pet_shadow", "pet_emotion_effect"],
    partSlots: [
      slot({ partKind: "pet_body_round", layer: "actorPartLayer", order: 10, repeatHint: 1, isRequired: true, offsetX: 0, offsetY: 0 }),
      slot({ partKind: "pet_ear_round", layer: "actorPartLayer", order: 20, repeatHint: 2, isRequired: false, offsetX: 0, offsetY: -7 }),
      slot({ partKind: "pet_tail_curled", layer: "actorPartLayer", order: 30, repeatHint: 1, isRequired: false, offsetX: 10, offsetY: 1 }),
      slot({ partKind: "emotion_sparkle", layer: "actorEffectLayer", order: 40, repeatHint: 2, isRequired: false, offsetX: 0, offsetY: -14 }),
    ],
    styleTags: ["pet_life", "warm", "adaptive"],
    stateTags: ["actor", "pet", "emotion"],
    unlockStageTags: ["actor_pet"],
    defaultEnabled: true,
  }),
  defineRule({
    kind: "interaction_feedback",
    target: "interaction",
    displayName: "点击反馈组合",
    description: "用点击涟漪组合可交互对象的短暂像素反馈。",
    targetWorldObjects: ["home_door", "garden_patch", "pet_arrival_point", "home_welcome_area"],
    partSlots: [
      slot({ partKind: "click_ripple", layer: "interactionLayer", order: 10, repeatHint: 1, isRequired: true, offsetX: 0, offsetY: 0 }),
    ],
    styleTags: ["home", "arrival", "warm"],
    stateTags: ["interaction", "feedback"],
    unlockStageTags: ["interaction"],
    defaultEnabled: true,
  }),
  defineRule({
    kind: "atmosphere",
    target: "environment",
    displayName: "环境氛围组合",
    description: "用环境光叠层表达时间、天气和命理风格带来的世界氛围。",
    targetWorldObjects: ["ambient_light", "weather_overlay"],
    partSlots: [
      slot({ partKind: "ambient_light_overlay", layer: "atmosphereLayer", order: 10, repeatHint: 1, isRequired: true, offsetX: 0, offsetY: 0 }),
    ],
    styleTags: ["quiet", "warm", "aesthetic", "adaptive"],
    stateTags: ["atmosphere", "time"],
    unlockStageTags: ["environment_light"],
    defaultEnabled: true,
  }),
]
