/**
 * 当前文件负责：注册像素世界渲染图层顺序。
 */

import type { PixelRenderLayerDefinition } from "./pixel-render-layer-schema"

export const PIXEL_RENDER_LAYERS: PixelRenderLayerDefinition[] = [
  {
    id: "groundBaseLayer",
    order: 10,
    purpose: "ground",
    displayName: "地面基础层",
    description: "草地、土地等最底层地表。",
    acceptsPartCategories: ["ground"],
    defaultVisible: true,
    blocksInteraction: false,
  },
  {
    id: "groundDetailLayer",
    order: 20,
    purpose: "detail",
    displayName: "地面细节层",
    description: "花草、杂草、脚印、维护痕迹等地面细节。",
    acceptsPartCategories: ["ground", "environment", "effect"],
    defaultVisible: true,
    blocksInteraction: false,
  },
  {
    id: "pathLayer",
    order: 30,
    purpose: "path",
    displayName: "路径层",
    description: "家园小路、小镇道路和角色行动路线。",
    acceptsPartCategories: ["path"],
    defaultVisible: true,
    blocksInteraction: false,
  },
  {
    id: "structureBaseLayer",
    order: 40,
    purpose: "structure",
    displayName: "建筑底座层",
    description: "地基、庭院土地区块和大型结构底座。",
    acceptsPartCategories: ["home_structure", "home_facility", "town_structure"],
    defaultVisible: true,
    blocksInteraction: false,
  },
  {
    id: "structureLayer",
    order: 50,
    purpose: "structure",
    displayName: "建筑主体层",
    description: "房屋主体、围栏、领养中心主体和设施主体。",
    acceptsPartCategories: [
      "home_structure",
      "home_facility",
      "town_structure",
      "adoption_center",
    ],
    defaultVisible: true,
    blocksInteraction: false,
  },
  {
    id: "structureDetailLayer",
    order: 60,
    purpose: "structure",
    displayName: "建筑细节层",
    description: "门、窗、招牌、灯光、食物碗、水碗、宠物床等细节。",
    acceptsPartCategories: [
      "home_structure",
      "home_facility",
      "adoption_center",
      "effect",
    ],
    defaultVisible: true,
    blocksInteraction: false,
  },
  {
    id: "actorShadowLayer",
    order: 70,
    purpose: "actor",
    displayName: "角色阴影层",
    description: "宠物和管家的地面阴影。",
    acceptsPartCategories: ["pet", "butler", "effect"],
    defaultVisible: true,
    blocksInteraction: false,
  },
  {
    id: "actorLayer",
    order: 80,
    purpose: "actor",
    displayName: "角色主体层",
    description: "管家和宠物的主体图形。",
    acceptsPartCategories: ["pet", "butler"],
    defaultVisible: true,
    blocksInteraction: false,
  },
  {
    id: "actorPartLayer",
    order: 90,
    purpose: "actor",
    displayName: "角色部件层",
    description: "管家工具、衣服、宠物耳朵、尾巴等可组合部件。",
    acceptsPartCategories: ["pet", "butler"],
    defaultVisible: true,
    blocksInteraction: false,
  },
  {
    id: "actorEffectLayer",
    order: 100,
    purpose: "effect",
    displayName: "角色效果层",
    description: "宠物和管家的情绪、行动、状态小特效。",
    acceptsPartCategories: ["effect", "pet", "butler"],
    defaultVisible: true,
    blocksInteraction: false,
  },
  {
    id: "interactionLayer",
    order: 110,
    purpose: "interaction",
    displayName: "交互反馈层",
    description: "点击涟漪、可观察提示、抵达点提示等交互反馈。",
    acceptsPartCategories: ["interaction", "effect", "adoption_center"],
    defaultVisible: true,
    blocksInteraction: false,
  },
  {
    id: "atmosphereLayer",
    order: 120,
    purpose: "atmosphere",
    displayName: "氛围叠层",
    description: "时间、天气、环境光和世界氛围覆盖层。",
    acceptsPartCategories: ["environment", "effect"],
    defaultVisible: true,
    blocksInteraction: false,
  },
  {
    id: "devOverlayLayer",
    order: 900,
    purpose: "development",
    displayName: "开发审计层",
    description: "F3 和开发审计使用的覆盖层，不属于正式玩家主体验。",
    acceptsPartCategories: ["effect", "interaction"],
    defaultVisible: false,
    blocksInteraction: true,
  },
]
