/**
 * 当前文件负责：注册像素世界中的业务对象定义。
 */

import type {
  PixelWorldObjectDefinition,
  WorldObjectBuildRole,
  WorldObjectCategory,
  WorldObjectInteractionRole,
  WorldObjectKind,
  WorldObjectPerceptionRole,
  WorldObjectStyleTag,
} from "./world-object-schema"

function defineObject(input: {
  kind: WorldObjectKind
  category: WorldObjectCategory
  displayName: string
  description: string
  defaultVisible?: boolean
  interactionRoles?: WorldObjectInteractionRole[]
  buildRole?: WorldObjectBuildRole
  perceptionRole?: WorldObjectPerceptionRole
  styleTags?: WorldObjectStyleTag[]
  requiredStageTags?: string[]
  unlockHint?: string
  notes?: string
}): PixelWorldObjectDefinition {
  return {
    id: `pixel-world-object-${input.kind}`,
    kind: input.kind,
    category: input.category,
    displayName: input.displayName,
    description: input.description,
    defaultVisible: input.defaultVisible ?? true,
    interactionRoles: input.interactionRoles ?? ["none"],
    buildRole: input.buildRole ?? "none",
    perceptionRole: input.perceptionRole ?? "player_observe",
    styleTags: input.styleTags ?? [],
    requiredStageTags: input.requiredStageTags ?? [],
    unlockHint: input.unlockHint ?? "初始世界对象。",
    notes: input.notes,
  }
}

export const PIXEL_WORLD_OBJECTS: PixelWorldObjectDefinition[] = [
  defineObject({
    kind: "home_land",
    category: "home",
    displayName: "家园空地",
    description: "玩家家园最初展开的土地，也是后续空间成长的基础。",
    buildRole: "land",
    perceptionRole: "both_sense",
    styleTags: ["home", "quiet", "adaptive"],
    requiredStageTags: ["home_initial"],
  }),
  defineObject({
    kind: "home_boundary",
    category: "home",
    displayName: "家园边界",
    description: "家园和外部世界之间的可感知边界。",
    interactionRoles: ["observable"],
    buildRole: "boundary",
    perceptionRole: "both_sense",
    styleTags: ["home", "boundary", "protective"],
    requiredStageTags: ["home_initial"],
  }),
  defineObject({
    kind: "home_path",
    category: "path",
    displayName: "家园小路",
    description: "连接家园入口、住所和活动点的基础路径。",
    interactionRoles: ["observable"],
    buildRole: "path",
    perceptionRole: "both_sense",
    styleTags: ["home", "order", "structured"],
    requiredStageTags: ["home_path"],
  }),
  defineObject({
    kind: "temporary_shelter",
    category: "home",
    displayName: "临时住所",
    description: "早期家园中最基础的遮蔽与生活空间。",
    interactionRoles: ["clickable", "enter", "observable", "build_target"],
    buildRole: "shelter",
    perceptionRole: "both_sense",
    styleTags: ["home", "warm", "protective", "comfort"],
    requiredStageTags: ["temporary_shelter"],
  }),
  defineObject({
    kind: "home_foundation",
    category: "home",
    displayName: "家园地基",
    description: "住所成长为稳定结构前的基础支撑。",
    interactionRoles: ["observable", "build_target"],
    buildRole: "structure",
    perceptionRole: "butler_sense",
    styleTags: ["structured", "stability", "home"],
    requiredStageTags: ["foundation"],
  }),
  defineObject({
    kind: "home_wall",
    category: "home",
    displayName: "家园墙体",
    description: "形成住所空间感与安全感的结构对象。",
    interactionRoles: ["observable", "build_target"],
    buildRole: "structure",
    perceptionRole: "both_sense",
    styleTags: ["structured", "protective", "home"],
    requiredStageTags: ["frame"],
  }),
  defineObject({
    kind: "home_roof",
    category: "home",
    displayName: "家园屋顶",
    description: "提升遮蔽感、稳定感和家园完成度的结构对象。",
    interactionRoles: ["observable", "build_target"],
    buildRole: "structure",
    perceptionRole: "player_observe",
    styleTags: ["protective", "stability", "home"],
    requiredStageTags: ["roof"],
  }),
  defineObject({
    kind: "home_door",
    category: "interaction",
    displayName: "家园门",
    description: "室内外切换与家园进入感的核心交互对象。",
    interactionRoles: ["clickable", "enter", "exit", "observable"],
    buildRole: "structure",
    perceptionRole: "both_sense",
    styleTags: ["home", "warm", "structured"],
    requiredStageTags: ["temporary_shelter"],
  }),
  defineObject({
    kind: "home_window",
    category: "home",
    displayName: "家园窗",
    description: "表达家园内外连通和光线变化的结构对象。",
    interactionRoles: ["observable"],
    buildRole: "comfort",
    perceptionRole: "player_observe",
    styleTags: ["warm", "aesthetic", "home"],
    requiredStageTags: ["frame"],
  }),
  defineObject({
    kind: "home_light",
    category: "effect",
    displayName: "家园灯光",
    description: "表达安全、温暖、时段变化与家园状态的光效对象。",
    interactionRoles: ["observable"],
    buildRole: "comfort",
    perceptionRole: "both_sense",
    styleTags: ["warm", "comfort", "quiet", "home"],
    requiredStageTags: ["interior"],
  }),
  defineObject({
    kind: "home_fence",
    category: "home",
    displayName: "家园围栏",
    description: "强化家园边界和早期空间秩序的结构对象。",
    interactionRoles: ["observable", "build_target"],
    buildRole: "boundary",
    perceptionRole: "both_sense",
    styleTags: ["boundary", "order", "protective", "home"],
    requiredStageTags: ["garden"],
  }),
  defineObject({
    kind: "garden_patch",
    category: "facility",
    displayName: "小庭院地块",
    description: "后续观察、探索和轻量活动的自然空间对象。",
    interactionRoles: ["clickable", "observable", "inspect", "pet_focus"],
    buildRole: "garden",
    perceptionRole: "both_sense",
    styleTags: ["garden", "comfort", "adaptive", "pet_life"],
    requiredStageTags: ["garden"],
  }),
  defineObject({
    kind: "observation_spot",
    category: "interaction",
    displayName: "观察点",
    description: "宠物、管家和玩家都可以感知世界边界的位置。",
    interactionRoles: ["clickable", "observable", "inspect", "pet_focus"],
    buildRole: "comfort",
    perceptionRole: "both_sense",
    styleTags: ["quiet", "boundary", "pet_life"],
    requiredStageTags: ["activity_area"],
  }),
  defineObject({
    kind: "storage_box",
    category: "facility",
    displayName: "整理箱",
    description: "表达家园秩序和物资管理的基础设施。",
    interactionRoles: ["observable", "build_target"],
    buildRole: "storage",
    perceptionRole: "butler_sense",
    styleTags: ["order", "structured", "home"],
    requiredStageTags: ["storage_area"],
  }),
  defineObject({
    kind: "food_corner",
    category: "facility",
    displayName: "食物角落",
    description: "宠物未来进食和管家照看行为的基础设施对象。",
    interactionRoles: ["observable", "build_target", "pet_focus"],
    buildRole: "care",
    perceptionRole: "both_sense",
    styleTags: ["care", "comfort", "pet_life"],
    requiredStageTags: ["basic_living"],
  }),
  defineObject({
    kind: "water_corner",
    category: "facility",
    displayName: "饮水角落",
    description: "宠物饮水、环境湿度和照看秩序的基础设施对象。",
    interactionRoles: ["observable", "build_target", "pet_focus"],
    buildRole: "care",
    perceptionRole: "both_sense",
    styleTags: ["care", "stability", "pet_life"],
    requiredStageTags: ["basic_living"],
  }),
  defineObject({
    kind: "pet_bed",
    category: "facility",
    displayName: "宠物休息垫",
    description: "宠物休息、睡眠和安全感表达的基础设施对象。",
    interactionRoles: ["observable", "build_target", "pet_focus"],
    buildRole: "comfort",
    perceptionRole: "both_sense",
    styleTags: ["comfort", "warm", "pet_life", "home"],
    requiredStageTags: ["basic_living"],
  }),

  defineObject({
    kind: "town_gate",
    category: "town",
    displayName: "小镇入口",
    description: "连接玩家家园与小镇服务的远景入口对象。",
    defaultVisible: false,
    interactionRoles: ["observable"],
    buildRole: "town_service",
    perceptionRole: "player_observe",
    styleTags: ["town", "boundary", "structured"],
    requiredStageTags: ["town_unlocked"],
    unlockHint: "小镇内容开放后可见。",
  }),
  defineObject({
    kind: "town_path",
    category: "town",
    displayName: "小镇道路",
    description: "管家前往小镇服务点时的路线对象。",
    defaultVisible: false,
    interactionRoles: ["observable"],
    buildRole: "town_service",
    perceptionRole: "butler_sense",
    styleTags: ["town", "order", "structured"],
    requiredStageTags: ["town_unlocked"],
    unlockHint: "小镇路线开放后可见。",
  }),
  defineObject({
    kind: "town_square",
    category: "town",
    displayName: "小镇广场",
    description: "未来小镇服务和公共空间的基础场景对象。",
    defaultVisible: false,
    interactionRoles: ["observable"],
    buildRole: "town_service",
    perceptionRole: "player_observe",
    styleTags: ["town", "warm", "aesthetic"],
    requiredStageTags: ["town_unlocked"],
    unlockHint: "小镇场景开放后可见。",
  }),
  defineObject({
    kind: "adoption_center",
    category: "adoption_center",
    displayName: "宠物领养中心",
    description: "管家前往小镇报名领养宠物的服务对象。",
    defaultVisible: false,
    interactionRoles: ["observable", "inspect", "butler_focus"],
    buildRole: "town_service",
    perceptionRole: "butler_sense",
    styleTags: ["town", "arrival", "care", "structured"],
    requiredStageTags: ["town_adoption_center"],
    unlockHint: "领养中心场景开放后可见。",
  }),
  defineObject({
    kind: "adoption_sign",
    category: "adoption_center",
    displayName: "领养中心招牌",
    description: "标记领养中心入口和服务性质的视觉对象。",
    defaultVisible: false,
    interactionRoles: ["observable", "inspect"],
    buildRole: "town_service",
    perceptionRole: "player_observe",
    styleTags: ["town", "arrival", "warm"],
    requiredStageTags: ["town_adoption_center"],
  }),
  defineObject({
    kind: "adoption_counter",
    category: "adoption_center",
    displayName: "领养登记柜台",
    description: "管家提交领养申请和等待审核的服务点。",
    defaultVisible: false,
    interactionRoles: ["observable", "inspect", "butler_focus"],
    buildRole: "town_service",
    perceptionRole: "butler_sense",
    styleTags: ["town", "structured", "care"],
    requiredStageTags: ["town_adoption_center"],
  }),
  defineObject({
    kind: "adoption_waiting_area",
    category: "adoption_center",
    displayName: "领养等待区",
    description: "表达审核、分配和等待宠物送达的空间对象。",
    defaultVisible: false,
    interactionRoles: ["observable", "inspect"],
    buildRole: "town_service",
    perceptionRole: "player_observe",
    styleTags: ["town", "quiet", "arrival"],
    requiredStageTags: ["town_adoption_center"],
  }),
  defineObject({
    kind: "adoption_notice_board",
    category: "adoption_center",
    displayName: "领养公告板",
    description: "展示领养中心规则、审核状态和分配提示的对象。",
    defaultVisible: false,
    interactionRoles: ["observable", "inspect"],
    buildRole: "town_service",
    perceptionRole: "player_observe",
    styleTags: ["town", "structured", "order"],
    requiredStageTags: ["town_adoption_center"],
  }),
  defineObject({
    kind: "pet_arrival_point",
    category: "adoption_center",
    displayName: "宠物抵达点",
    description: "宠物被送达玩家家园时的世界关系建立点。",
    interactionRoles: ["clickable", "observable", "arrival_focus"],
    buildRole: "care",
    perceptionRole: "both_sense",
    styleTags: ["arrival", "care", "warm", "pet_life"],
    requiredStageTags: ["pet_arrival"],
  }),
  defineObject({
    kind: "butler_town_route",
    category: "town",
    displayName: "管家小镇路线",
    description: "管家从家园前往小镇服务点的抽象路线对象。",
    defaultVisible: false,
    interactionRoles: ["observable", "butler_focus"],
    buildRole: "town_service",
    perceptionRole: "butler_sense",
    styleTags: ["town", "order", "arrival"],
    requiredStageTags: ["town_route"],
  }),
  defineObject({
    kind: "home_welcome_area",
    category: "home",
    displayName: "家园迎接区",
    description: "宠物抵达家园后，玩家、管家和宠物建立关系的初始区域。",
    interactionRoles: ["clickable", "observable", "arrival_focus"],
    buildRole: "care",
    perceptionRole: "both_sense",
    styleTags: ["arrival", "home", "warm", "pet_life"],
    requiredStageTags: ["pet_arrival"],
  }),

  defineObject({
    kind: "butler_actor",
    category: "actor",
    displayName: "管家角色",
    description: "管家的像素角色对象，用于表现管理、照看和行动。",
    interactionRoles: ["observable", "butler_focus"],
    perceptionRole: "player_observe",
    styleTags: ["structured", "protective", "care"],
    requiredStageTags: ["actor_butler"],
  }),
  defineObject({
    kind: "butler_tool",
    category: "actor",
    displayName: "管家工具",
    description: "管家进行建设、整理和照看时携带或使用的工具对象。",
    interactionRoles: ["observable"],
    buildRole: "facility",
    perceptionRole: "player_observe",
    styleTags: ["order", "structured", "care"],
    requiredStageTags: ["actor_butler"],
  }),
  defineObject({
    kind: "butler_emotion_effect",
    category: "effect",
    displayName: "管家情绪效果",
    description: "表达管家专注、温和、保护等状态的像素效果。",
    interactionRoles: ["observable"],
    perceptionRole: "player_observe",
    styleTags: ["warm", "protective", "quiet"],
    requiredStageTags: ["actor_butler"],
  }),
  defineObject({
    kind: "pet_actor",
    category: "pet",
    displayName: "宠物角色",
    description: "宠物抵达家园后的像素角色对象。",
    interactionRoles: ["observable", "pet_focus"],
    perceptionRole: "player_observe",
    styleTags: ["pet_life", "adaptive", "warm"],
    requiredStageTags: ["actor_pet"],
  }),
  defineObject({
    kind: "pet_shadow",
    category: "pet",
    displayName: "宠物影子",
    description: "增强宠物站位、运动和体积感的基础表现对象。",
    interactionRoles: ["none"],
    perceptionRole: "player_observe",
    styleTags: ["quiet", "pet_life"],
    requiredStageTags: ["actor_pet"],
  }),
  defineObject({
    kind: "pet_emotion_effect",
    category: "effect",
    displayName: "宠物情绪效果",
    description: "表达宠物好奇、警觉、疲惫、温暖等状态的像素效果。",
    interactionRoles: ["observable"],
    perceptionRole: "player_observe",
    styleTags: ["pet_life", "adaptive", "warm"],
    requiredStageTags: ["actor_pet"],
  }),

  defineObject({
    kind: "grass_base",
    category: "ground",
    displayName: "基础草地",
    description: "家园和世界边界的基础地表对象。",
    interactionRoles: ["none"],
    buildRole: "land",
    perceptionRole: "both_sense",
    styleTags: ["garden", "home", "quiet"],
    requiredStageTags: ["ground_base"],
  }),
  defineObject({
    kind: "grass_detail",
    category: "ground",
    displayName: "草地细节",
    description: "增强地面变化和像素自然感的细节对象。",
    interactionRoles: ["none"],
    buildRole: "land",
    perceptionRole: "player_observe",
    styleTags: ["garden", "aesthetic", "adaptive"],
    requiredStageTags: ["ground_detail"],
  }),
  defineObject({
    kind: "grass_flower",
    category: "environment",
    displayName: "小花",
    description: "表达家园舒适度、季节感和温暖氛围的环境对象。",
    interactionRoles: ["observable"],
    buildRole: "garden",
    perceptionRole: "both_sense",
    styleTags: ["garden", "aesthetic", "comfort"],
    requiredStageTags: ["garden"],
  }),
  defineObject({
    kind: "grass_weed",
    category: "environment",
    displayName: "杂草",
    description: "表达家园维护需求、自然扩张和轻微失序的环境对象。",
    interactionRoles: ["observable"],
    buildRole: "land",
    perceptionRole: "both_sense",
    styleTags: ["garden", "adaptive", "order"],
    requiredStageTags: ["ground_detail"],
  }),
  defineObject({
    kind: "dirt_path",
    category: "path",
    displayName: "泥土小路",
    description: "早期家园和小镇路线的低保真路径对象。",
    interactionRoles: ["observable"],
    buildRole: "path",
    perceptionRole: "both_sense",
    styleTags: ["order", "home", "town"],
    requiredStageTags: ["path_basic"],
  }),
  defineObject({
    kind: "stone_path",
    category: "path",
    displayName: "石板路",
    description: "更稳定、更有秩序的家园或小镇路径对象。",
    interactionRoles: ["observable"],
    buildRole: "path",
    perceptionRole: "both_sense",
    styleTags: ["structured", "stability", "order"],
    requiredStageTags: ["path_stone"],
  }),
  defineObject({
    kind: "footprint_pet",
    category: "effect",
    displayName: "宠物脚印",
    description: "表达宠物移动轨迹和生命活动痕迹的短暂效果。",
    interactionRoles: ["observable"],
    perceptionRole: "player_observe",
    styleTags: ["pet_life", "adaptive", "quiet"],
    requiredStageTags: ["actor_pet"],
  }),
  defineObject({
    kind: "maintenance_mark",
    category: "effect",
    displayName: "维护标记",
    description: "表达管家整理、修复或维护行为的短暂像素标记。",
    interactionRoles: ["observable"],
    buildRole: "facility",
    perceptionRole: "player_observe",
    styleTags: ["order", "structured", "stability"],
    requiredStageTags: ["butler_action"],
  }),
  defineObject({
    kind: "ambient_light",
    category: "environment",
    displayName: "环境光",
    description: "表达时间、天气、家园温度和命理风格影响的基础环境对象。",
    interactionRoles: ["none"],
    perceptionRole: "player_observe",
    styleTags: ["quiet", "warm", "aesthetic"],
    requiredStageTags: ["environment_light"],
  }),
  defineObject({
    kind: "weather_overlay",
    category: "environment",
    displayName: "天气叠层",
    description: "表达天气、氛围和世界状态变化的轻量叠层对象。",
    interactionRoles: ["none"],
    perceptionRole: "player_observe",
    styleTags: ["adaptive", "quiet", "aesthetic"],
    requiredStageTags: ["weather"],
  }),
]
