/**
 * 当前文件职责：建立家园空间实体的初始结构。
 */

import type {
  HomeSpaceState,
} from "@/types/home"

export function createInitialHomeSpaces(): HomeSpaceState[] {
  return [
    {
      id: "empty_land",
      name: "初始空地",
      role: "origin",
      status: "active",
      order: 1,
      progress: 100,
      comfort: 20,
      stability: 35,
      activity: 10,
      description: "世界最初展开的空地，也是管家开始整理家园的地方。",
      tags: ["origin", "empty_land", "starting_area"],
    },
    {
      id: "initial_care_area",
      name: "初始照护区",
      role: "care",
      status: "active",
      order: 2,
      progress: 100,
      comfort: 35,
      stability: 55,
      activity: 20,
      description: "用于安置基础照护与管理工作的核心区域。",
      tags: ["initial_care", "early_world", "care_priority"],
    },
    {
      id: "temporary_shelter",
      name: "临时住所",
      role: "shelter",
      status: "building",
      order: 3,
      progress: 0,
      comfort: 25,
      stability: 30,
      activity: 15,
      description: "管家正在搭建的最初住所，为后续家园成长提供基础。",
      tags: ["shelter", "home_building", "butler_managed"],
    },
    {
      id: "garden_area",
      name: "庭院区域",
      role: "garden",
      status: "locked",
      order: 4,
      progress: 0,
      comfort: 20,
      stability: 20,
      activity: 10,
      description: "未来可供观察、靠近和探索的开放家园区域。",
      tags: ["garden", "future_space", "world_observation"],
    },
    {
      id: "storage_area",
      name: "储物区域",
      role: "storage",
      status: "locked",
      order: 5,
      progress: 0,
      comfort: 15,
      stability: 25,
      activity: 5,
      description: "用于放置基础物资和维护家园秩序的区域。",
      tags: ["storage", "order", "future_space"],
    },
    {
      id: "activity_area",
      name: "活动区域",
      role: "activity",
      status: "locked",
      order: 6,
      progress: 0,
      comfort: 20,
      stability: 20,
      activity: 20,
      description: "未来可能承载观察、互动和世界活动的开放区域。",
      tags: ["activity", "interaction_space", "future_space"],
    },
  ]
}
