/**
 * 当前文件职责：建立家园设施实体的初始结构。
 */

import type {
  HomeFacilityState,
} from "@/types/home"

export function createInitialHomeFacilities(): HomeFacilityState[] {
  return [
    {
      id: "basic_care_station",
      name: "基础照护台",
      role: "care",
      status: "active",
      spaceId: "initial_care_area",
      progress: 100,
      durability: 82,
      usefulness: 85,
      comfortBonus: 6,
      stabilityBonus: 12,
      activityBonus: 2,
      description: "用于支持管家观察、整理和基础照护工作的设施。",
      tags: ["starter_facility", "initial_care", "care_priority"],
    },
    {
      id: "shelter_bed",
      name: "临时休息垫",
      role: "rest",
      status: "planned",
      spaceId: "temporary_shelter",
      progress: 0,
      durability: 40,
      usefulness: 35,
      comfortBonus: 10,
      stabilityBonus: 3,
      activityBonus: 0,
      description: "未来用于提供基础休息环境的临时设施。",
      tags: ["rest", "temporary_shelter", "planned"],
    },
    {
      id: "food_corner",
      name: "食物角落",
      role: "food",
      status: "locked",
      spaceId: "temporary_shelter",
      progress: 0,
      durability: 35,
      usefulness: 30,
      comfortBonus: 3,
      stabilityBonus: 2,
      activityBonus: 1,
      description: "未来用于放置食物与照护物资的基础角落。",
      tags: ["food", "future_facility"],
    },
    {
      id: "water_corner",
      name: "饮水角落",
      role: "water",
      status: "locked",
      spaceId: "temporary_shelter",
      progress: 0,
      durability: 35,
      usefulness: 30,
      comfortBonus: 2,
      stabilityBonus: 3,
      activityBonus: 1,
      description: "未来用于提供基础饮水与环境湿度观察的角落。",
      tags: ["water", "future_facility"],
    },
    {
      id: "storage_box",
      name: "整理箱",
      role: "storage",
      status: "locked",
      spaceId: "storage_area",
      progress: 0,
      durability: 45,
      usefulness: 35,
      comfortBonus: 1,
      stabilityBonus: 10,
      activityBonus: 0,
      description: "用于提升家园秩序和基础物资管理的设施。",
      tags: ["storage", "order", "future_facility"],
    },
    {
      id: "garden_patch",
      name: "小庭院地块",
      role: "garden",
      status: "locked",
      spaceId: "garden_area",
      progress: 0,
      durability: 45,
      usefulness: 35,
      comfortBonus: 6,
      stabilityBonus: 4,
      activityBonus: 8,
      description: "未来可供观察与探索的小庭院设施。",
      tags: ["garden", "observation", "future_facility"],
    },
    {
      id: "observation_spot",
      name: "观察点",
      role: "observation",
      status: "locked",
      spaceId: "activity_area",
      progress: 0,
      durability: 40,
      usefulness: 30,
      comfortBonus: 3,
      stabilityBonus: 4,
      activityBonus: 10,
      description: "未来用于管家观察世界边界的开放点位。",
      tags: ["activity", "observation", "future_facility"],
    },
  ]
}
