/**
 * 当前文件负责：定义 MVP 初始家园的道路坐标层。
 */

import type { InitialHomePathLayer } from "../initial-home-map-schema"

export const INITIAL_HOME_PATH_LAYER: InitialHomePathLayer = {
  id: "initial-home-path-layer",
  name: "初始家园道路层",
  tiles: [
    { x: 18, y: 21, assetId: "pathDirtHorizontal01" },
    { x: 19, y: 21, assetId: "pathDirtHorizontal01" },
    { x: 20, y: 21, assetId: "pathDirtCornerRightBottom01" },
    { x: 20, y: 22, assetId: "pathDirtVertical01" },
    { x: 20, y: 23, assetId: "pathDirtCornerLeftTop01" },
    { x: 21, y: 23, assetId: "pathDirtHorizontal01" },
    { x: 22, y: 23, assetId: "pathDirtHorizontal01" },
    { x: 23, y: 23, assetId: "pathDirtCornerRightBottom01" },
    { x: 23, y: 24, assetId: "pathDirtVertical01" },
    { x: 23, y: 25, assetId: "pathDirtCornerLeftTop01" },
    { x: 24, y: 25, assetId: "pathDirtHorizontal01" },
    { x: 25, y: 25, assetId: "pathDirtHorizontal01" },
    { x: 26, y: 25, assetId: "pathDirtHorizontal01" },
    { x: 27, y: 25, assetId: "pathDirtCornerRightBottom01" },
    { x: 27, y: 26, assetId: "pathDirtVertical01" },
    { x: 27, y: 27, assetId: "pathDirtCornerLeftTop01" },
    { x: 28, y: 27, assetId: "pathDirtHorizontal01" },
    { x: 29, y: 27, assetId: "pathDirtHorizontal01" },
    { x: 30, y: 27, assetId: "pathDirtHorizontal01" },
    { x: 31, y: 27, assetId: "pathDirtCornerRightBottom01" },
    { x: 31, y: 28, assetId: "pathDirtVertical01" },
    { x: 31, y: 29, assetId: "pathDirtCornerLeftTop01" },
    { x: 32, y: 29, assetId: "pathDirtHorizontal01" },
    { x: 33, y: 29, assetId: "pathDirtHorizontal01" },
    { x: 34, y: 29, assetId: "pathDirtHorizontal01" },
    { x: 35, y: 29, assetId: "pathDirtHorizontal01" },
    { x: 36, y: 29, assetId: "pathDirtHorizontal01" },
    { x: 37, y: 29, assetId: "pathDirtHorizontal01" },
    { x: 38, y: 29, assetId: "pathDirtCornerRightTop01" },
    { x: 38, y: 28, assetId: "pathDirtVertical01" },
    { x: 38, y: 27, assetId: "pathDirtCornerLeftBottom01" },
    { x: 39, y: 27, assetId: "pathDirtHorizontal01" },
    { x: 40, y: 27, assetId: "pathDirtHorizontal01" },
    { x: 41, y: 27, assetId: "pathDirtHorizontal01" },
    { x: 42, y: 27, assetId: "pathDirtCornerRightTop01" },
    { x: 42, y: 26, assetId: "pathDirtVertical01" },
    { x: 42, y: 25, assetId: "pathDirtCornerLeftBottom01" },
    { x: 43, y: 25, assetId: "pathDirtHorizontal01" },
    { x: 44, y: 25, assetId: "pathDirtHorizontal01" },
    { x: 45, y: 25, assetId: "pathDirtCornerRightTop01" },
    { x: 45, y: 24, assetId: "pathDirtVertical01" },
    { x: 45, y: 23, assetId: "pathDirtCornerLeftBottom01" },
    { x: 46, y: 23, assetId: "pathDirtHorizontal01" },
    { x: 47, y: 23, assetId: "pathDirtHorizontal01" },
    { x: 48, y: 23, assetId: "pathDirtHorizontal01" },
    { x: 49, y: 23, assetId: "pathDirtCornerRightTop01" },
    { x: 49, y: 22, assetId: "pathDirtVertical01" },
    { x: 49, y: 21, assetId: "pathDirtCornerLeftBottom01" },
    { x: 50, y: 21, assetId: "pathDirtHorizontal01" },
    { x: 51, y: 21, assetId: "pathDirtHorizontal01" },
    { x: 52, y: 21, assetId: "pathDirtHorizontal01" },
  ],
}
