import { readFile } from "node:fs/promises"
import path from "node:path"
import { NextRequest, NextResponse } from "next/server"

export const runtime = "nodejs"
export const dynamic = "force-dynamic"

const views = {
  drafts: path.join("data", "ai-painter-datasets", "natural-home", "drafts", "contact-sheet.png"),
  imported: path.join("data", "ai-painter-datasets", "natural-home", "drafts", "imported-contact-sheet.png"),
  dataset: path.join(".runtime", "ai-painter", "natural-home-dataset", "contact-sheet.png"),
  cleanDataset: path.join(".runtime", "ai-painter", "natural-home-clean-dataset", "contact-sheet.png"),
  inference: path.join(".runtime", "ai-painter", "natural-home-inference", "natural-home-crop-v7-12-forest-stream-clean.png"),
  structureInference: path.join(".runtime", "ai-painter", "natural-home-structure-guided-inference", "generated.png"),
  structurePreview: path.join(".runtime", "ai-painter", "natural-home-structure-guided-inference", "structure-preview.png"),
  rgbRefinerInference: path.join(".runtime", "ai-painter", "natural-home-rgb-refiner-inference", "generated.png"),
  cleanStructureInference: path.join(".runtime", "ai-painter", "natural-home-clean-structure-guided-inference", "generated.png"),
  cleanStructurePreview: path.join(".runtime", "ai-painter", "natural-home-clean-structure-guided-inference", "structure-preview.png"),
  cleanRgbRefinerInference: path.join(".runtime", "ai-painter", "natural-home-clean-rgb-refiner-inference", "generated.png"),
  cleanRgbRefinerV2Inference: path.join(".runtime", "ai-painter", "natural-home-clean-rgb-refiner-v2-inference", "generated.png"),
  cleanRgbRefinerV3Inference: path.join(".runtime", "ai-painter", "natural-home-clean-rgb-refiner-v3-inference", "generated.png"),
  singleOverfitInference: path.join(".runtime", "ai-painter", "natural-home-single-overfit-inference", "generated.png"),
  singleDirectOverfitInference: path.join(".runtime", "ai-painter", "natural-home-single-direct-overfit-inference", "generated.png"),
  cleanDirectInference: path.join(".runtime", "ai-painter", "natural-home-clean-direct-inference", "generated.png"),
  localDetailInference: path.join(".runtime", "ai-painter", "natural-home-local-detail-inference", "contact-sheet.png"),
  localDetailV2Inference: path.join(".runtime", "ai-painter", "natural-home-local-detail-v2-inference", "contact-sheet.png"),
  localDetailV3Inference: path.join(".runtime", "ai-painter", "natural-home-local-detail-v3-inference", "contact-sheet.png"),
  localDetailV4GanInference: path.join(".runtime", "ai-painter", "natural-home-local-detail-v4-gan-inference", "contact-sheet.png"),
  localDetailV5DiscreteInference: path.join(".runtime", "ai-painter", "natural-home-local-detail-v5-discrete-inference", "contact-sheet.png"),
  localDetailV6SingleOverfitInference: path.join(".runtime", "ai-painter", "natural-home-local-detail-v6-single-overfit-inference", "contact-sheet.png"),
  localDetailV7SourceCurriculumInference: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-local-detail-v7-source-curriculum-inference",
    "contact-sheet.png",
  ),
  localDetailV8VisualCurriculumInference: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-local-detail-v8-visual-curriculum-inference",
    "contact-sheet.png",
  ),
  localDetailV9CategoryDetailUnetInference: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-local-detail-v9-category-detail-unet-inference",
    "contact-sheet.png",
  ),
  localDetailV10SourceLockedInference: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-local-detail-v10-source-locked-inference",
    "contact-sheet.png",
  ),
  localDetailV11MultisourceInference: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-local-detail-v11-multisource-inference",
    "contact-sheet.png",
  ),
  localDetailV12SourceConditionedInference: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-local-detail-v12-source-conditioned-inference",
    "contact-sheet.png",
  ),
  localDetailV13SourceExpertRoute: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-local-detail-v13-source-expert-route",
    "contact-sheet.png",
  ),
  localDetailV14SingleSourceCompose: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-local-detail-v14-single-source-compose-inference",
    "contact-sheet.png",
  ),
  localDetailV15MultisourceCompose: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-local-detail-v15-multisource-compose-inference",
    "contact-sheet.png",
  ),
  localDetailV16StyleMultisourceCompose: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-local-detail-v16-style-multisource-compose-inference",
    "contact-sheet.png",
  ),
  localDetailV17SourceExpertCompose: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-local-detail-v17-source-expert-compose-inference",
    "contact-sheet.png",
  ),
  localDetailV18SourceExpertBank: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-local-detail-v18-source-expert-bank",
    "contact-sheet.png",
  ),
  localDetailV19PromotedSource: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-local-detail-v19-promoted-source",
    "contact-sheet.png",
  ),
  localDetailV20MultisourceGeneralization: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-local-detail-v20-multisource-generalization",
    "contact-sheet.png",
  ),
  localDetailV22WarningFocus: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-local-detail-v22-warning-focus",
    "contact-sheet.png",
  ),
  localDetailV23CandidateConsolidation: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-local-detail-v23-candidate-consolidation",
    "contact-sheet.png",
  ),
  naturalHomeV24DiversityGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v24-diversity-generation",
    "contact-sheet.png",
  ),
  naturalHomeV25DiversityGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v25-diversity-generation",
    "contact-sheet.png",
  ),
  naturalHomeV26DiversityRefinerGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v26-diversity-refiner-generation",
    "contact-sheet.png",
  ),
  naturalHomeV27DiversityRefinerGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v27-diversity-refiner-generation",
    "contact-sheet.png",
  ),
  naturalHomeV28DiversityRefinerGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v28-diversity-refiner-generation",
    "contact-sheet.png",
  ),
  naturalHomeV29DiverseSourceRefinerGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v29-diverse-source-refiner-generation",
    "contact-sheet.png",
  ),
  naturalHomeV30QualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v30-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV31EdgeRefinerGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v31-edge-refiner-generation",
    "contact-sheet.png",
  ),
  naturalHomeV31QualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v31-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV32PatchganRefinerGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v32-patchgan-refiner-generation",
    "contact-sheet.png",
  ),
  naturalHomeV32QualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v32-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV33WaterArtifactGuardGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v33-water-artifact-guard-generation",
    "contact-sheet.png",
  ),
  naturalHomeV33QualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v33-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV34WaterStabilityGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v34-water-stability-generation",
    "contact-sheet.png",
  ),
  naturalHomeV34QualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v34-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV35BalancedWaterDetailGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v35-balanced-water-detail-generation",
    "contact-sheet.png",
  ),
  naturalHomeV35QualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v35-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV36BalancedGeneralizationGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v36-balanced-generalization-generation",
    "contact-sheet.png",
  ),
  naturalHomeV36QualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v36-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV37WaterFailureRepairGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v37-water-failure-repair-generation",
    "contact-sheet.png",
  ),
  naturalHomeV37QualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v37-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV38WaterEdgeBalanceGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v38-water-edge-balance-generation",
    "contact-sheet.png",
  ),
  naturalHomeV38QualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v38-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV39FailureFocusRepairGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v39-failure-focus-repair-generation",
    "contact-sheet.png",
  ),
  naturalHomeV39QualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v39-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV40SharpnessLockRepairGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v40-sharpness-lock-repair-generation",
    "contact-sheet.png",
  ),
  naturalHomeV40QualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v40-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV41V32WaterRescueGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v41-v32-water-rescue-generation",
    "contact-sheet.png",
  ),
  naturalHomeV41QualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v41-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV42WaterExpertFixGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v42-v32-water-expert-fix-generation",
    "contact-sheet.png",
  ),
  naturalHomeV42QualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v42-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV43V32FailureFocusRepairGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v43-v32-failure-focus-repair-generation",
    "contact-sheet.png",
  ),
  naturalHomeV43QualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v43-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV44V32StableGeneralizationGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v44-v32-stable-generalization-generation",
    "contact-sheet.png",
  ),
  naturalHomeV44QualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v44-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV45GeneralizationGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v45-generalization-generation",
    "contact-sheet.png",
  ),
  naturalHomeV45QualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v45-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV46V45FailureFocusRepairGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v46-v45-failure-focus-repair-generation",
    "contact-sheet.png",
  ),
  naturalHomeV46QualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v46-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV47HardFailureStabilizationGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v47-hard-failure-stabilization-generation",
    "contact-sheet.png",
  ),
  naturalHomeV47QualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v47-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV48WaterSharpnessExpertFixGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v48-water-sharpness-expert-fix-generation",
    "contact-sheet.png",
  ),
  naturalHomeV48RepairQualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v48-repair-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV48MergeGateSelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v48-merge-gate-selection",
    "contact-sheet.png",
  ),
  naturalHomeV49V32DiversitySweepGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v49-v32-diversity-sweep-generation",
    "contact-sheet.png",
  ),
  naturalHomeV49QualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v49-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV50DiversityWaterGate: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v50-diversity-water-gate",
    "contact-sheet.png",
  ),
  naturalHomeV51SafeCandidatePack: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v51-safe-candidate-pack",
    "contact-sheet.png",
  ),
  naturalHomeV91CurrentMvpGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v91-current-mvp-quality-ready-generation",
    "contact-sheet.png",
  ),
  naturalHomeV91CurrentMvpQualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v91-current-mvp-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV91CurrentMvpVj1Review: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v91-current-mvp-vj1-review",
    "contact-sheet.png",
  ),
  naturalHomeV91CurrentMvpVj2Review: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v91-current-mvp-vj2-review",
    "contact-sheet.png",
  ),
  naturalHomeV91ApprovedFrameCandidateBinding: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v91-approved-frame-candidate-binding",
    "candidate-preview.png",
  ),
  naturalHomeV92GeneralizationSweepGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v92-current-mvp-generalization-sweep-generation",
    "contact-sheet.png",
  ),
  naturalHomeV92GeneralizationQualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v92-current-mvp-generalization-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV92GeneralizationVj1Review: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v92-current-mvp-generalization-vj1-review",
    "contact-sheet.png",
  ),
  naturalHomeV92GeneralizationVj2Review: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v92-current-mvp-generalization-vj2-review",
    "contact-sheet.png",
  ),
  naturalHomeV93CleanGeneralizationDataset: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v93-clean-generalization-dataset",
    "contact-sheet.png",
  ),
  naturalHomeV93CleanGeneralizationGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v93-clean-generalization-generation",
    "contact-sheet.png",
  ),
  naturalHomeV93CleanGeneralizationQualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v93-clean-generalization-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV93CleanGeneralizationVj1Review: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v93-clean-generalization-vj1-review",
    "contact-sheet.png",
  ),
  naturalHomeV93CleanGeneralizationVj2Review: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v93-clean-generalization-vj2-review",
    "contact-sheet.png",
  ),
  naturalHomeV94EdgeSharpnessRepairGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v94-edge-sharpness-repair-generation",
    "contact-sheet.png",
  ),
  naturalHomeV94EdgeSharpnessRepairQualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v94-edge-sharpness-repair-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV94EdgeSharpnessRepairVj1Review: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v94-edge-sharpness-repair-vj1-review",
    "contact-sheet.png",
  ),
  naturalHomeV94EdgeSharpnessRepairVj2Review: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v94-edge-sharpness-repair-vj2-review",
    "contact-sheet.png",
  ),
  naturalHomeV95FailureRepairDataset: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v95-failure-repair-dataset",
    "contact-sheet.png",
  ),
  naturalHomeV95FailureRepairGeneration: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v95-failure-repair-generation",
    "contact-sheet.png",
  ),
  naturalHomeV95FailureRepairQualitySelection: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v95-failure-repair-quality-selection",
    "contact-sheet.png",
  ),
  naturalHomeV95FailureRepairVj1Review: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v95-failure-repair-vj1-review",
    "contact-sheet.png",
  ),
  naturalHomeV95FailureRepairVj2Review: path.join(
    ".runtime",
    "ai-painter",
    "natural-home-v95-failure-repair-vj2-review",
    "contact-sheet.png",
  ),
} as const

export async function GET(_request: NextRequest, context: { params: Promise<{ view: string }> }) {
  if (process.env.NODE_ENV === "production") return new NextResponse(null, { status: 403 })
  const { view } = await context.params
  const file = views[view as keyof typeof views]
  if (!file) return new NextResponse(null, { status: 404 })
  try {
    const image = await readFile(path.join(process.cwd(), file))
    return new NextResponse(image, { headers: { "content-type": "image/png", "cache-control": "no-store" } })
  } catch {
    return new NextResponse(null, { status: 404 })
  }
}
