/**
 * 当前文件负责：提供像素 Sprite Sheet 占位元数据索引。
 */

import type {
  SpriteFrameMetadata,
  SpriteMetadataIndex,
  SpriteSheetMetadata,
  SpriteVariantMapping,
} from "./sprite-metadata.types"

function buildFrame(input: SpriteFrameMetadata): SpriteFrameMetadata {
  return input
}

const butlerFrames: SpriteFrameMetadata[] = [
  buildFrame({
    id: "butler_structured_compact_v1_idle_0",
    sheetId: "actors_butlers_v1",
    category: "butler",
    name: "秩序建设型管家待机帧",
    rect: { x: 0, y: 0, width: 32, height: 48 },
    anchor: { x: 16, y: 44 },
    gridSize: { columns: 2, rows: 3 },
    tags: {
      archetype: "structured_builder",
      colorTone: "metal_clear",
      butlerSilhouette: "steady_compact",
    },
    description: "稳定、方正、衣着整齐，适合秩序建设型玩家的管家外观。",
  }),
  buildFrame({
    id: "butler_soft_round_v1_idle_0",
    sheetId: "actors_butlers_v1",
    category: "butler",
    name: "温暖照护型管家待机帧",
    rect: { x: 32, y: 0, width: 32, height: 48 },
    anchor: { x: 16, y: 44 },
    gridSize: { columns: 2, rows: 3 },
    tags: {
      archetype: "warm_caretaker",
      colorTone: "earth_warm",
      butlerSilhouette: "soft_round",
    },
    description: "暖色、柔和、照护感更强，适合温暖照护型玩家。",
  }),
  buildFrame({
    id: "butler_guarded_upright_v1_idle_0",
    sheetId: "actors_butlers_v1",
    category: "butler",
    name: "边界守护型管家待机帧",
    rect: { x: 64, y: 0, width: 32, height: 48 },
    anchor: { x: 16, y: 44 },
    gridSize: { columns: 2, rows: 3 },
    tags: {
      archetype: "protective_keeper",
      colorTone: "wood_green",
      butlerSilhouette: "guarded_upright",
    },
    description: "直立、边界感更强，适合保护和观察型管家。",
  }),
  buildFrame({
    id: "butler_elegant_light_v1_idle_0",
    sheetId: "actors_butlers_v1",
    category: "butler",
    name: "审美整理型管家待机帧",
    rect: { x: 96, y: 0, width: 32, height: 48 },
    anchor: { x: 16, y: 44 },
    gridSize: { columns: 2, rows: 3 },
    tags: {
      archetype: "aesthetic_organizer",
      colorTone: "fire_bright",
      butlerSilhouette: "elegant_light",
    },
    description: "轻盈、有装饰感，适合审美整理型家园。",
  }),
  buildFrame({
    id: "butler_quiet_simple_v1_idle_0",
    sheetId: "actors_butlers_v1",
    category: "butler",
    name: "安静维护型管家待机帧",
    rect: { x: 128, y: 0, width: 32, height: 48 },
    anchor: { x: 16, y: 44 },
    gridSize: { columns: 2, rows: 3 },
    tags: {
      archetype: "quiet_maintainer",
      colorTone: "water_quiet",
      butlerSilhouette: "quiet_simple",
    },
    description: "低调、稳定、少装饰，适合安静维护型玩家。",
  }),
  buildFrame({
    id: "butler_balanced_adaptive_v1_idle_0",
    sheetId: "actors_butlers_v1",
    category: "butler",
    name: "适应规划型管家待机帧",
    rect: { x: 160, y: 0, width: 32, height: 48 },
    anchor: { x: 16, y: 44 },
    gridSize: { columns: 2, rows: 3 },
    tags: {
      archetype: "adaptive_planner",
      colorTone: "moon_soft",
      butlerSilhouette: "balanced_adaptive",
    },
    description: "平衡、混合、适合根据资源和宠物状态动态调整。",
  }),
]

const petFrames: SpriteFrameMetadata[] = [
  buildFrame({
    id: "pet_stable_attached_v1_idle_0",
    sheetId: "actors_pets_v1",
    category: "pet",
    name: "稳定依恋型宠物待机帧",
    rect: { x: 0, y: 0, width: 32, height: 32 },
    anchor: { x: 16, y: 30 },
    gridSize: { columns: 2, rows: 2 },
    tags: { petMatchType: "stable_attached", colorTone: "metal_clear" },
    description: "稳定、亲近、体型偏圆稳的宠物外观。",
  }),
  buildFrame({
    id: "pet_soft_companion_v1_idle_0",
    sheetId: "actors_pets_v1",
    category: "pet",
    name: "柔软陪伴型宠物待机帧",
    rect: { x: 32, y: 0, width: 32, height: 32 },
    anchor: { x: 16, y: 30 },
    gridSize: { columns: 2, rows: 2 },
    tags: { petMatchType: "soft_companion", colorTone: "earth_warm" },
    description: "柔和、圆润、低攻击性，更强调陪伴感。",
  }),
  buildFrame({
    id: "pet_alert_guardian_v1_idle_0",
    sheetId: "actors_pets_v1",
    category: "pet",
    name: "警觉守护型宠物待机帧",
    rect: { x: 64, y: 0, width: 32, height: 32 },
    anchor: { x: 16, y: 30 },
    gridSize: { columns: 2, rows: 2 },
    tags: { petMatchType: "alert_guardian", colorTone: "wood_green" },
    description: "耳朵更明显、站姿更警觉，适合边界守护型家园。",
  }),
  buildFrame({
    id: "pet_curious_playful_v1_idle_0",
    sheetId: "actors_pets_v1",
    category: "pet",
    name: "好奇活泼型宠物待机帧",
    rect: { x: 96, y: 0, width: 32, height: 32 },
    anchor: { x: 16, y: 30 },
    gridSize: { columns: 2, rows: 2 },
    tags: { petMatchType: "curious_playful", colorTone: "fire_bright" },
    description: "体态更轻、更亮，尾巴或耳朵更活跃。",
  }),
  buildFrame({
    id: "pet_quiet_observer_v1_idle_0",
    sheetId: "actors_pets_v1",
    category: "pet",
    name: "安静观察型宠物待机帧",
    rect: { x: 128, y: 0, width: 32, height: 32 },
    anchor: { x: 16, y: 30 },
    gridSize: { columns: 2, rows: 2 },
    tags: { petMatchType: "quiet_observer", colorTone: "water_quiet" },
    description: "低饱和、眼神安静、动作幅度小。",
  }),
  buildFrame({
    id: "pet_adaptive_partner_v1_idle_0",
    sheetId: "actors_pets_v1",
    category: "pet",
    name: "适应伙伴型宠物待机帧",
    rect: { x: 160, y: 0, width: 32, height: 32 },
    anchor: { x: 16, y: 30 },
    gridSize: { columns: 2, rows: 2 },
    tags: { petMatchType: "adaptive_partner", colorTone: "moon_soft" },
    description: "混合体态，可随场景变化。",
  }),
]

const buildingFrames: SpriteFrameMetadata[] = [
  buildFrame({
    id: "shelter_straight_frame_v1_base_0",
    sheetId: "buildings_home_v1",
    category: "building",
    name: "直线框架临时住所",
    rect: { x: 0, y: 0, width: 80, height: 64 },
    anchor: { x: 40, y: 60 },
    gridSize: { columns: 5, rows: 4 },
    tags: { shelterStyle: "straight_frame", homeStyle: "orderly_structured" },
    description: "HOME-02 阶段的秩序型临时住所。",
  }),
  buildFrame({
    id: "shelter_soft_canopy_v1_base_0",
    sheetId: "buildings_home_v1",
    category: "building",
    name: "柔和遮蔽临时住所",
    rect: { x: 80, y: 0, width: 80, height: 64 },
    anchor: { x: 40, y: 60 },
    gridSize: { columns: 5, rows: 4 },
    tags: { shelterStyle: "soft_canopy", homeStyle: "warm_care_first" },
    description: "HOME-02 阶段的温暖照护型临时住所。",
  }),
  buildFrame({
    id: "shelter_reinforced_edge_v1_base_0",
    sheetId: "buildings_home_v1",
    category: "building",
    name: "加固边界临时住所",
    rect: { x: 160, y: 0, width: 80, height: 64 },
    anchor: { x: 40, y: 60 },
    gridSize: { columns: 5, rows: 4 },
    tags: { shelterStyle: "reinforced_edge", homeStyle: "protected_boundary" },
    description: "HOME-02 阶段的边界防护型临时住所。",
  }),
  buildFrame({
    id: "home_orderly_structured_v1_base_0",
    sheetId: "buildings_home_v1",
    category: "building",
    name: "秩序结构型基础小屋",
    rect: { x: 0, y: 64, width: 96, height: 80 },
    anchor: { x: 48, y: 76 },
    gridSize: { columns: 6, rows: 5 },
    tags: { homeStyle: "orderly_structured", colorTone: "metal_clear" },
    description: "HOME-03 阶段基础小屋，占地 6x5 tile。",
  }),
  buildFrame({
    id: "home_warm_care_first_v1_base_0",
    sheetId: "buildings_home_v1",
    category: "building",
    name: "温暖照护型基础小屋",
    rect: { x: 96, y: 64, width: 96, height: 80 },
    anchor: { x: 48, y: 76 },
    gridSize: { columns: 6, rows: 5 },
    tags: { homeStyle: "warm_care_first", colorTone: "earth_warm" },
    description: "HOME-03 阶段暖色照护型基础小屋。",
  }),
]

const facilityFrames: SpriteFrameMetadata[] = [
  buildFrame({
    id: "care_storage_first_v1_base_0",
    sheetId: "facilities_care_v1",
    category: "facility",
    name: "储物优先照护角",
    rect: { x: 0, y: 0, width: 80, height: 48 },
    anchor: { x: 40, y: 44 },
    gridSize: { columns: 5, rows: 3 },
    tags: { carePriority: "storage_first" },
    description: "储物、整理和资源管理更明显的照护角。",
  }),
  buildFrame({
    id: "care_comfort_first_v1_base_0",
    sheetId: "facilities_care_v1",
    category: "facility",
    name: "舒适优先照护角",
    rect: { x: 80, y: 0, width: 80, height: 48 },
    anchor: { x: 40, y: 44 },
    gridSize: { columns: 5, rows: 3 },
    tags: { carePriority: "comfort_first" },
    description: "宠物床、食物碗、水碗更突出的照护角。",
  }),
  buildFrame({
    id: "care_safety_first_v1_base_0",
    sheetId: "facilities_care_v1",
    category: "facility",
    name: "安全优先照护角",
    rect: { x: 160, y: 0, width: 80, height: 48 },
    anchor: { x: 40, y: 44 },
    gridSize: { columns: 5, rows: 3 },
    tags: { carePriority: "safety_first" },
    description: "观察点和边界感更强的照护角。",
  }),
]

const tileFrames: SpriteFrameMetadata[] = [
  buildFrame({
    id: "tile_grass_base_v1_0",
    sheetId: "tiles_ground_v1",
    category: "tile",
    name: "基础草地 Tile",
    rect: { x: 0, y: 0, width: 16, height: 16 },
    anchor: { x: 0, y: 0 },
    gridSize: { columns: 1, rows: 1 },
    tags: { gardenStyle: "mixed_natural" },
    description: "可重复拼接的基础草地。",
  }),
  buildFrame({
    id: "tile_dirt_path_v1_0",
    sheetId: "tiles_path_v1",
    category: "tile",
    name: "泥路 Tile",
    rect: { x: 0, y: 0, width: 16, height: 16 },
    anchor: { x: 0, y: 0 },
    gridSize: { columns: 1, rows: 1 },
    tags: { homeStyle: "orderly_structured" },
    description: "可重复拼接的泥土路径。",
  }),
]

const sheets: SpriteSheetMetadata[] = [
  {
    id: "actors_butlers_v1",
    imagePath: "/assets/pixel/actors/butlers/actors_butlers_v1.png",
    tileSize: 16,
    pixelScale: 4,
    category: "butler",
    frameWidth: 32,
    frameHeight: 48,
    frames: butlerFrames,
    animations: [{ id: "idle", frameIds: butlerFrames.map((frame) => frame.id), frameDurationMs: 600, loop: true }],
    notes: "MVP 6 类管家待机帧占位索引，真实图片后续补充。",
  },
  {
    id: "actors_pets_v1",
    imagePath: "/assets/pixel/actors/pets/actors_pets_v1.png",
    tileSize: 16,
    pixelScale: 4,
    category: "pet",
    frameWidth: 32,
    frameHeight: 32,
    frames: petFrames,
    animations: [{ id: "idle", frameIds: petFrames.map((frame) => frame.id), frameDurationMs: 600, loop: true }],
    notes: "MVP 6 类宠物待机帧占位索引，真实图片后续补充。",
  },
  {
    id: "buildings_home_v1",
    imagePath: "/assets/pixel/buildings/buildings_home_v1.png",
    tileSize: 16,
    pixelScale: 4,
    category: "building",
    frameWidth: 96,
    frameHeight: 80,
    frames: buildingFrames,
    animations: [{ id: "base", frameIds: buildingFrames.map((frame) => frame.id), frameDurationMs: 1000, loop: false }],
    notes: "临时住所和基础小屋 sprite 占位索引。",
  },
  {
    id: "facilities_care_v1",
    imagePath: "/assets/pixel/facilities/facilities_care_v1.png",
    tileSize: 16,
    pixelScale: 4,
    category: "facility",
    frameWidth: 80,
    frameHeight: 48,
    frames: facilityFrames,
    animations: [{ id: "base", frameIds: facilityFrames.map((frame) => frame.id), frameDurationMs: 1000, loop: false }],
    notes: "照护角 sprite 占位索引。",
  },
  {
    id: "tiles_ground_v1",
    imagePath: "/assets/pixel/tiles/ground.png",
    tileSize: 16,
    pixelScale: 4,
    category: "tile",
    frameWidth: 16,
    frameHeight: 16,
    frames: tileFrames.filter((frame) => frame.sheetId === "tiles_ground_v1"),
    animations: [{ id: "base", frameIds: ["tile_grass_base_v1_0"], frameDurationMs: 1000, loop: false }],
    notes: "地面 tile 占位索引。",
  },
  {
    id: "tiles_path_v1",
    imagePath: "/assets/pixel/tiles/path.png",
    tileSize: 16,
    pixelScale: 4,
    category: "tile",
    frameWidth: 16,
    frameHeight: 16,
    frames: tileFrames.filter((frame) => frame.sheetId === "tiles_path_v1"),
    animations: [{ id: "base", frameIds: ["tile_dirt_path_v1_0"], frameDurationMs: 1000, loop: false }],
    notes: "路径 tile 占位索引。",
  },
]

const variantMappings: SpriteVariantMapping[] = [
  ...butlerFrames.map((frame) => ({
    spriteVariantId: frame.id.replace("_idle_0", ""),
    frameId: frame.id,
    sheetId: frame.sheetId,
    animationId: "idle" as const,
    description: frame.description,
  })),
  ...petFrames.map((frame) => ({
    spriteVariantId: frame.id.replace("_idle_0", ""),
    frameId: frame.id,
    sheetId: frame.sheetId,
    animationId: "idle" as const,
    description: frame.description,
  })),
  ...buildingFrames.map((frame) => ({
    spriteVariantId: frame.id.replace("_base_0", ""),
    frameId: frame.id,
    sheetId: frame.sheetId,
    animationId: "base" as const,
    description: frame.description,
  })),
  ...facilityFrames.map((frame) => ({
    spriteVariantId: frame.id.replace("_base_0", ""),
    frameId: frame.id,
    sheetId: frame.sheetId,
    animationId: "base" as const,
    description: frame.description,
  })),
]

export const spriteMetadataIndex: SpriteMetadataIndex = {
  sheets,
  variantMappings,
}

export const spriteFrames = [
  ...butlerFrames,
  ...petFrames,
  ...buildingFrames,
  ...facilityFrames,
  ...tileFrames,
]
