/**
 * 当前文件职责：登记世界地图素材资源。
 */

import type { WorldMapAssetDefinition } from "./world-map-asset-schema"

export const WORLD_MAP_ASSETS = {
  groundGrassBase01: {
    id: "groundGrassBase01",
    category: "ground",
    path: "/assets/generated/world/ground/ground_grass_base_01.png",
    baseSize: 32,
    anchor: "top-left",
    description: "基础草地 tile",
  },
  groundGrassBase02: {
    id: "groundGrassBase02",
    category: "ground",
    path: "/assets/generated/world/ground/ground_grass_variant_01.png",
    baseSize: 32,
    anchor: "top-left",
    description: "草地变化 tile",
  },
  groundDirtBase01: {
    id: "groundDirtBase01",
    category: "ground",
    path: "/assets/generated/world/ground/ground_dirt_base_01.png",
    baseSize: 32,
    anchor: "top-left",
    description: "基础泥地 tile",
  },
  pathDirtHorizontal01: {
    id: "pathDirtHorizontal01",
    category: "path",
    path: "/assets/generated/world/paths/path_dirt_horizontal_01.png",
    baseSize: 32,
    anchor: "top-left",
    description: "横向泥路 tile",
  },
  pathDirtVertical01: {
    id: "pathDirtVertical01",
    category: "path",
    path: "/assets/generated/world/paths/path_dirt_vertical_01.png",
    baseSize: 32,
    anchor: "top-left",
    description: "纵向泥路 tile",
  },
  pathDirtCornerLeftTop01: {
    id: "pathDirtCornerLeftTop01",
    category: "path",
    path: "/assets/generated/world/paths/path_dirt_corner_left_top_01.png",
    baseSize: 32,
    anchor: "top-left",
    description: "泥路左上拐角",
  },
  pathDirtCornerRightTop01: {
    id: "pathDirtCornerRightTop01",
    category: "path",
    path: "/assets/generated/world/paths/path_dirt_corner_right_top_01.png",
    baseSize: 32,
    anchor: "top-left",
    description: "泥路右上拐角",
  },
  pathDirtCornerLeftBottom01: {
    id: "pathDirtCornerLeftBottom01",
    category: "path",
    path: "/assets/generated/world/paths/path_dirt_corner_left_bottom_01.png",
    baseSize: 32,
    anchor: "top-left",
    description: "泥路左下拐角",
  },
  pathDirtCornerRightBottom01: {
    id: "pathDirtCornerRightBottom01",
    category: "path",
    path: "/assets/generated/world/paths/path_dirt_corner_right_bottom_01.png",
    baseSize: 32,
    anchor: "top-left",
    description: "泥路右下拐角",
  },
  edgeGrassDirtTop01: {
    id: "edgeGrassDirtTop01",
    category: "edge",
    path: "/assets/generated/world/edges/edge_grass_dirt_grass_top_01.png",
    baseSize: 32,
    anchor: "top-left",
    description: "草地泥地上边缘",
  },
  edgeGrassDirtBottom01: {
    id: "edgeGrassDirtBottom01",
    category: "edge",
    path: "/assets/generated/world/edges/edge_grass_dirt_dirt_top_01.png",
    baseSize: 32,
    anchor: "top-left",
    description: "草地泥地下边缘",
  },
  edgeGrassDirtLeft01: {
    id: "edgeGrassDirtLeft01",
    category: "edge",
    path: "/assets/generated/world/edges/edge_grass_dirt_grass_left_01.png",
    baseSize: 32,
    anchor: "top-left",
    description: "草地泥地左边缘",
  },
  edgeGrassDirtRight01: {
    id: "edgeGrassDirtRight01",
    category: "edge",
    path: "/assets/generated/world/edges/edge_grass_dirt_dirt_left_01.png",
    baseSize: 32,
    anchor: "top-left",
    description: "草地泥地右边缘",
  },
  zoneInitialEmptyLandTrace01: {
    id: "zoneInitialEmptyLandTrace01",
    category: "zone",
    path: "/assets/generated/world/zones/zone_initial_empty_land_trace_01.png",
    baseSize: 128,
    anchor: "bottom-center",
    description: "初始空地痕迹",
  },
  arrivalPointGrassRingSoft01: {
    id: "arrivalPointGrassRingSoft01",
    category: "structure",
    path: "/assets/generated/home/arrival-point/arrival_point_grass_ring_soft_01.png",
    baseSize: 128,
    anchor: "bottom-center",
    description: "初始入口草环",
  },
  buildingTempShelterCanvasTent01: {
    id: "buildingTempShelterCanvasTent01",
    category: "structure",
    path: "/assets/generated/home/buildings/temp-shelter/building_temp_shelter_canvas_tent_01.png",
    baseSize: 128,
    anchor: "bottom-center",
    description: "临时住所帆布帐篷",
  },
  buildingTempShelter01: {
    id: "buildingTempShelter01",
    category: "structure",
    path: "/assets/generated/home/buildings/temp-shelter/building_temp_shelter_basic_tent_01.png",
    baseSize: 128,
    anchor: "bottom-center",
    description: "临时住所",
  },
  buildingPetArrivalPoint01: {
    id: "buildingPetArrivalPoint01",
    category: "structure",
    path: "/assets/generated/home/arrival-point/arrival_point_grass_ring_soft_01.png",
    baseSize: 128,
    anchor: "bottom-center",
    description: "后置生命关系阶段可使用的入口素材",
  },
  buildingInitialCareStation01: {
    id: "buildingInitialCareStation01",
    category: "structure",
    path: "/assets/generated/world/zones/zone_initial_care_soft_grass_01.png",
    baseSize: 128,
    anchor: "bottom-center",
    description: "初始照护点",
  },
  facilityFoodBowlFull01: {
    id: "facilityFoodBowlFull01",
    category: "facility",
    path: "/assets/generated/home/facilities/facility_food_bowl_full_01.png",
    baseSize: 64,
    anchor: "bottom-center",
    description: "基础食物容器素材",
  },
  facilityWaterBowlFull01: {
    id: "facilityWaterBowlFull01",
    category: "facility",
    path: "/assets/generated/home/facilities/facility_water_bowl_full_01.png",
    baseSize: 64,
    anchor: "bottom-center",
    description: "基础饮水容器素材",
  },
  facilityPetBedNeat01: {
    id: "facilityPetBedNeat01",
    category: "facility",
    path: "/assets/generated/home/facilities/facility_pet_bed_neat_01.png",
    baseSize: 64,
    anchor: "bottom-center",
    description: "后置生命关系阶段可使用的休息素材",
  },
  facilityStorageBoxClosed01: {
    id: "facilityStorageBoxClosed01",
    category: "facility",
    path: "/assets/generated/home/facilities/facility_storage_box_closed_01.png",
    baseSize: 64,
    anchor: "bottom-center",
    description: "储物箱",
  },
  facilityLampOn01: {
    id: "facilityLampOn01",
    category: "facility",
    path: "/assets/generated/home/facilities/facility_lamp_on_01.png",
    baseSize: 64,
    anchor: "bottom-center",
    description: "临时小灯",
  },
  natureTreeSmall01: {
    id: "natureTreeSmall01",
    category: "nature",
    path: "/assets/generated/world/nature/nature_tree_small_round_01.png",
    baseSize: 64,
    anchor: "bottom-center",
    description: "小树",
  },
  natureBushRoundLow01: {
    id: "natureBushRoundLow01",
    category: "nature",
    path: "/assets/generated/world/nature/nature_bush_round_low_01.png",
    baseSize: 64,
    anchor: "bottom-center",
    description: "低矮灌木",
  },
  natureBushSmall01: {
    id: "natureBushSmall01",
    category: "nature",
    path: "/assets/generated/world/nature/nature_bush_round_low_01.png",
    baseSize: 64,
    anchor: "bottom-center",
    description: "小灌木",
  },
  surfaceGrassTuftLow01: {
    id: "surfaceGrassTuftLow01",
    category: "surface_decoration",
    path: "/assets/generated/world/surface/surface_grass_tuft_low_01.png",
    baseSize: 32,
    anchor: "bottom-center",
    description: "低矮草丛",
  },
  surfaceGrassTuft01: {
    id: "surfaceGrassTuft01",
    category: "surface_decoration",
    path: "/assets/generated/world/surface/surface_grass_tuft_low_01.png",
    baseSize: 32,
    anchor: "bottom-center",
    description: "草丛",
  },
  surfaceStoneSmall01: {
    id: "surfaceStoneSmall01",
    category: "surface_decoration",
    path: "/assets/generated/world/surface/surface_stone_small_01.png",
    baseSize: 32,
    anchor: "bottom-center",
    description: "小石头",
  },
  surfaceFlowerPatch01: {
    id: "surfaceFlowerPatch01",
    category: "surface_decoration",
    path: "/assets/generated/world/surface/surface_flower_patch_white_01.png",
    baseSize: 32,
    anchor: "bottom-center",
    description: "小花",
  },
  surfaceFallenLeaf01: {
    id: "surfaceFallenLeaf01",
    category: "surface_decoration",
    path: "/assets/generated/world/surface/surface_fallen_leaf_green_01.png",
    baseSize: 32,
    anchor: "bottom-center",
    description: "落叶",
  },
  butlerBodyStandard01: {
    id: "butlerBodyStandard01",
    category: "actor",
    path: "/assets/generated/world/actors/butler_body_standard_01.png",
    baseSize: 64,
    anchor: "bottom-center",
    description: "管家标准身体",
  },
  petPartBodyRound01: {
    id: "petPartBodyRound01",
    category: "actor",
    path: "/assets/generated/world/actors/pet_part_body_round_01.png",
    baseSize: 64,
    anchor: "bottom-center",
    description: "后置宠物关系阶段可使用的身体素材",
  },
  petPoseSkeletonIdleFront01: {
    id: "petPoseSkeletonIdleFront01",
    category: "actor",
    path: "/assets/generated/world/actors/pet_pose_skeleton_idle_front_01.png",
    baseSize: 64,
    anchor: "bottom-center",
    description: "后置宠物关系阶段可使用的姿态素材",
  },
} as const satisfies Record<string, WorldMapAssetDefinition>

export type WorldMapAssetId = keyof typeof WORLD_MAP_ASSETS

export function getWorldMapAssetPath(assetId: WorldMapAssetId): string {
  return WORLD_MAP_ASSETS[assetId].path
}
