/**
 * Registers semantic world asset IDs used by runtime facts.
 */

import type { WorldMapAssetDefinition } from "./world-map-asset-schema"

export const WORLD_MAP_ASSETS = {
  groundGrassBase01: {
    id: "groundGrassBase01",
    category: "ground",
    baseSize: 32,
    anchor: "top-left",
    description: "基础草地",
  },
  groundGrassBase02: {
    id: "groundGrassBase02",
    category: "ground",
    baseSize: 32,
    anchor: "top-left",
    description: "草地变化",
  },
  groundDirtBase01: {
    id: "groundDirtBase01",
    category: "ground",
    baseSize: 32,
    anchor: "top-left",
    description: "基础泥地",
  },
  pathDirtHorizontal01: {
    id: "pathDirtHorizontal01",
    category: "path",
    baseSize: 32,
    anchor: "top-left",
    description: "横向泥路",
  },
  pathDirtVertical01: {
    id: "pathDirtVertical01",
    category: "path",
    baseSize: 32,
    anchor: "top-left",
    description: "纵向泥路",
  },
  pathDirtCornerLeftTop01: {
    id: "pathDirtCornerLeftTop01",
    category: "path",
    baseSize: 32,
    anchor: "top-left",
    description: "泥路左上转角",
  },
  pathDirtCornerRightTop01: {
    id: "pathDirtCornerRightTop01",
    category: "path",
    baseSize: 32,
    anchor: "top-left",
    description: "泥路右上转角",
  },
  pathDirtCornerLeftBottom01: {
    id: "pathDirtCornerLeftBottom01",
    category: "path",
    baseSize: 32,
    anchor: "top-left",
    description: "泥路左下转角",
  },
  pathDirtCornerRightBottom01: {
    id: "pathDirtCornerRightBottom01",
    category: "path",
    baseSize: 32,
    anchor: "top-left",
    description: "泥路右下转角",
  },
  edgeGrassDirtTop01: {
    id: "edgeGrassDirtTop01",
    category: "edge",
    baseSize: 32,
    anchor: "top-left",
    description: "草地泥地上边缘",
  },
  edgeGrassDirtBottom01: {
    id: "edgeGrassDirtBottom01",
    category: "edge",
    baseSize: 32,
    anchor: "top-left",
    description: "草地泥地下边缘",
  },
  edgeGrassDirtLeft01: {
    id: "edgeGrassDirtLeft01",
    category: "edge",
    baseSize: 32,
    anchor: "top-left",
    description: "草地泥地左边缘",
  },
  edgeGrassDirtRight01: {
    id: "edgeGrassDirtRight01",
    category: "edge",
    baseSize: 32,
    anchor: "top-left",
    description: "草地泥地右边缘",
  },
  zoneInitialEmptyLandTrace01: {
    id: "zoneInitialEmptyLandTrace01",
    category: "zone",
    baseSize: 128,
    anchor: "bottom-center",
    description: "初始空地痕迹",
  },
  arrivalPointGrassRingSoft01: {
    id: "arrivalPointGrassRingSoft01",
    category: "structure",
    baseSize: 128,
    anchor: "bottom-center",
    description: "初始入口草环",
  },
  buildingTempShelterTent01: {
    id: "buildingTempShelterTent01",
    category: "structure",
    baseSize: 128,
    anchor: "bottom-center",
    description: "临时住所帐篷",
  },
  buildingTempShelter01: {
    id: "buildingTempShelter01",
    category: "structure",
    baseSize: 128,
    anchor: "bottom-center",
    description: "临时住所",
  },
  buildingInitialCareStation01: {
    id: "buildingInitialCareStation01",
    category: "structure",
    baseSize: 128,
    anchor: "bottom-center",
    description: "初始照护点",
  },
  facilityFoodBowlFull01: {
    id: "facilityFoodBowlFull01",
    category: "facility",
    baseSize: 64,
    anchor: "bottom-center",
    description: "基础食物容器",
  },
  facilityWaterBowlFull01: {
    id: "facilityWaterBowlFull01",
    category: "facility",
    baseSize: 64,
    anchor: "bottom-center",
    description: "基础饮水容器",
  },
  facilityStorageBoxClosed01: {
    id: "facilityStorageBoxClosed01",
    category: "facility",
    baseSize: 64,
    anchor: "bottom-center",
    description: "储物箱",
  },
  facilityLampOn01: {
    id: "facilityLampOn01",
    category: "facility",
    baseSize: 64,
    anchor: "bottom-center",
    description: "临时小灯",
  },
  natureTreeSmall01: {
    id: "natureTreeSmall01",
    category: "nature",
    baseSize: 64,
    anchor: "bottom-center",
    description: "小树",
  },
  natureBushRoundLow01: {
    id: "natureBushRoundLow01",
    category: "nature",
    baseSize: 64,
    anchor: "bottom-center",
    description: "低矮灌木",
  },
  natureBushSmall01: {
    id: "natureBushSmall01",
    category: "nature",
    baseSize: 64,
    anchor: "bottom-center",
    description: "小灌木",
  },
  surfaceGrassTuftLow01: {
    id: "surfaceGrassTuftLow01",
    category: "surface_decoration",
    baseSize: 32,
    anchor: "bottom-center",
    description: "低矮草丛",
  },
  surfaceGrassTuft01: {
    id: "surfaceGrassTuft01",
    category: "surface_decoration",
    baseSize: 32,
    anchor: "bottom-center",
    description: "草丛",
  },
  surfaceStoneSmall01: {
    id: "surfaceStoneSmall01",
    category: "surface_decoration",
    baseSize: 32,
    anchor: "bottom-center",
    description: "小石头",
  },
  surfaceFlowerPatch01: {
    id: "surfaceFlowerPatch01",
    category: "surface_decoration",
    baseSize: 32,
    anchor: "bottom-center",
    description: "小花",
  },
  surfaceFallenLeaf01: {
    id: "surfaceFallenLeaf01",
    category: "surface_decoration",
    baseSize: 32,
    anchor: "bottom-center",
    description: "落叶",
  },
  butlerBodyStandard01: {
    id: "butlerBodyStandard01",
    category: "actor",
    baseSize: 64,
    anchor: "bottom-center",
    description: "管家标准身体",
  },
} as const satisfies Record<string, WorldMapAssetDefinition>

export type WorldMapAssetId = keyof typeof WORLD_MAP_ASSETS
