/**
 * Defines the current initial home scene recipe.
 */

import type { InitialHomeSceneRecipe } from "./generation-schema"

export const INITIAL_HOME_SCENE_RECIPE: InitialHomeSceneRecipe = {
  id: "runtime-initial-home-scene-recipe",
  name: "Runtime 初始家园 Scene Recipe",
  mapSize: {
    columns: 80,
    rows: 48,
    tileSize: 24,
  },
  visualCenter: {
    start: { x: 18, y: 14 },
    end: { x: 62, y: 34 },
  },
  areas: [
    {
      id: "visual-center-area",
      areaType: "visual_center",
      name: "视觉中心范围",
      purpose: "集中展示初始入口区、照护区、临时住所区与路径关系。",
      center: { x: 40, y: 24 },
      size: { width: 45, height: 21 },
      requiredAssets: [
        "groundGrassBase01",
        "pathDirtHorizontal01",
        "buildingTempShelter01",
      ],
      optionalAssets: ["surfaceGrassTuft01", "surfaceStoneSmall01"],
      forbiddenTags: ["old_birth_device"],
      density: "medium",
      pathConnections: ["entry_area", "initial_care", "temporary_shelter"],
      supportRules: ["核心区域必须聚合", "主路径必须连续"],
      tags: ["recipe_area", "visual_center"],
    },
    {
      id: "entry-area",
      areaType: "entry_area",
      name: "初始入口区",
      purpose: "表达家园第一幕的入口位置与世界观察起点。",
      center: { x: 18, y: 22 },
      size: { width: 10, height: 8 },
      requiredAssets: [],
      optionalAssets: ["surfaceGrassTuft01", "surfaceStoneSmall01"],
      forbiddenTags: ["old_birth_device"],
      density: "low",
      pathConnections: ["initial_care"],
      supportRules: ["抵达点必须落在草地或区域痕迹中"],
      tags: ["recipe_area", "entry_area"],
    },
    {
      id: "initial-care-area",
      areaType: "initial_care",
      name: "初始照护区",
      purpose: "提供最初的水、整理、观察与基础生活支持。",
      center: { x: 35, y: 29 },
      size: { width: 10, height: 7 },
      requiredAssets: ["buildingInitialCareStation01"],
      optionalAssets: ["surfaceFlowerPatch01", "facilityStorageBoxClosed01"],
      forbiddenTags: ["old_birth_device"],
      density: "medium",
      pathConnections: ["entry_area", "temporary_shelter"],
      supportRules: ["照护设施必须有泥地或踏痕承托"],
      tags: ["recipe_area", "care"],
    },
    {
      id: "temporary-shelter-area",
      areaType: "temporary_shelter",
      name: "临时住所区",
      purpose: "表达家园第一阶段的遮蔽、整理和居住支持。",
      center: { x: 52, y: 21 },
      size: { width: 12, height: 9 },
      requiredAssets: ["buildingTempShelter01"],
      optionalAssets: ["surfaceFallenLeaf01", "natureBushSmall01"],
      forbiddenTags: ["final_large_house", "old_birth_device"],
      density: "low",
      pathConnections: ["initial_care", "quiet_living", "storage_tools"],
      supportRules: ["临时住所必须有泥地承托"],
      tags: ["recipe_area", "shelter"],
    },
    {
      id: "quiet-living-area",
      areaType: "quiet_living",
      name: "安静生活区",
      purpose: "给初始家园提供靠近住所的安静生活与缓冲空间。",
      center: { x: 55, y: 29 },
      size: { width: 8, height: 5 },
      requiredAssets: [],
      optionalAssets: ["surfaceGrassTuft01"],
      forbiddenTags: ["isolated_bed"],
      density: "low",
      pathConnections: ["temporary_shelter"],
      supportRules: ["安静生活区必须靠近临时住所或照护区"],
      tags: ["recipe_area", "quiet_living"],
    },
    {
      id: "storage-tools-area",
      areaType: "storage_tools",
      name: "储物工具区",
      purpose: "表达管家整理资源、工具和基础建设材料的位置。",
      center: { x: 40, y: 30 },
      size: { width: 7, height: 5 },
      requiredAssets: ["facilityStorageBoxClosed01"],
      optionalAssets: ["surfaceStoneSmall01"],
      forbiddenTags: ["isolated_storage"],
      density: "low",
      pathConnections: ["initial_care", "temporary_shelter"],
      supportRules: ["储物箱必须贴近路径或照护区"],
      tags: ["recipe_area", "storage"],
    },
    {
      id: "natural-boundary-area",
      areaType: "natural_boundary",
      name: "自然边界区",
      purpose: "减少大面积空草地，并形成温暖自然的边界。",
      center: { x: 40, y: 24 },
      size: { width: 80, height: 48 },
      requiredAssets: ["natureTreeSmall01", "natureBushSmall01"],
      optionalAssets: [
        "surfaceGrassTuft01",
        "surfaceStoneSmall01",
        "surfaceFlowerPatch01",
        "surfaceFallenLeaf01",
      ],
      forbiddenTags: ["path_blocker"],
      density: "high",
      pathConnections: [],
      supportRules: ["自然物件不能阻断主路径"],
      tags: ["recipe_area", "nature_boundary"],
    },
  ],
  tags: [
    "scene_recipe",
    "runtime_initial_home",
    "placement_engine_required",
    "no_ai_free_layout",
  ],
}
