/**
 * 当前文件负责：定义 24 组合的视觉概率修正。
 */

import type {
  ZiweiPairId,
  ZiweiPreferenceBias,
} from "./ziwei-probability.types"
import { createPreferenceBias } from "./ziwei-preference-helpers"

export const ziweiPairPreferenceBiases: Record<
  ZiweiPairId,
  ZiweiPreferenceBias
> = {
  ziwei_tianfu: createPreferenceBias({
    archetypeScores: { structured_builder: 68, quiet_maintainer: 58 },
    petMatchScores: { stable_attached: 60, quiet_observer: 40 },
    visualScores: { order: 64, stability: 70 },
    colorToneHints: ["metal_clear", "earth_warm"],
    homeStyleHints: ["orderly_structured", "quiet_minimal"],
    gardenStyleHints: ["neat_low_grass"],
    shelterStyleHints: ["straight_frame"],
    carePriorityHints: ["storage_first", "stability_first"],
    explanation: "紫微天府强化管理与资源稳定，提升结构化和安静维护倾向。",
  }),
  ziwei_tanlang: createPreferenceBias({
    archetypeScores: { aesthetic_organizer: 72 },
    petMatchScores: { curious_playful: 58 },
    visualScores: { decoration: 78, order: 36 },
    colorToneHints: ["fire_bright", "metal_clear"],
    homeStyleHints: ["flowered_aesthetic"],
    gardenStyleHints: ["decorative_garden"],
    shelterStyleHints: ["decorated_roof"],
    carePriorityHints: ["beauty_first"],
    explanation: "紫微贪狼把中心感转向审美表达，提升装饰和花园倾向。",
  }),
  ziwei_qisha: createPreferenceBias({
    archetypeScores: { protective_keeper: 76 },
    petMatchScores: { alert_guardian: 66 },
    visualScores: { protection: 82, order: 42 },
    colorToneHints: ["wood_green", "metal_clear"],
    homeStyleHints: ["protected_boundary"],
    gardenStyleHints: ["protected_shrub_edge"],
    shelterStyleHints: ["reinforced_edge"],
    carePriorityHints: ["safety_first"],
    explanation: "紫微七杀把管理感转成行动防御，提升守护边界倾向。",
  }),
  ziwei_pojun: createPreferenceBias({
    archetypeScores: { adaptive_planner: 78 },
    petMatchScores: { adaptive_partner: 64 },
    visualScores: { nature: 54, protection: 48 },
    colorToneHints: ["moon_soft", "metal_clear"],
    homeStyleHints: ["adaptive_mixed"],
    gardenStyleHints: ["mixed_natural"],
    shelterStyleHints: ["adaptive_shelter"],
    carePriorityHints: ["context_first"],
    explanation: "紫微破军把管理感转成重建规划，提升适应型场景倾向。",
  }),
  tianji_taiyin: createPreferenceBias({
    archetypeScores: { quiet_maintainer: 62, adaptive_planner: 56 },
    petMatchScores: { quiet_observer: 60, adaptive_partner: 42 },
    visualScores: { stability: 58, nature: 48 },
    colorToneHints: ["moon_soft", "water_quiet"],
    homeStyleHints: ["quiet_minimal", "adaptive_mixed"],
    gardenStyleHints: ["quiet_shade", "mixed_natural"],
    shelterStyleHints: ["low_quiet_shelter", "adaptive_shelter"],
    carePriorityHints: ["stability_first", "context_first"],
    explanation: "天机太阴结合规划与细腻，提升安静维护和适应规划。",
  }),
  tianji_jumen: createPreferenceBias({
    archetypeScores: { protective_keeper: 60, adaptive_planner: 58 },
    petMatchScores: { alert_guardian: 54, adaptive_partner: 48 },
    visualScores: { protection: 64, nature: 46 },
    colorToneHints: ["wood_green", "moon_soft"],
    homeStyleHints: ["protected_boundary", "adaptive_mixed"],
    gardenStyleHints: ["protected_shrub_edge", "mixed_natural"],
    shelterStyleHints: ["reinforced_edge", "adaptive_shelter"],
    carePriorityHints: ["safety_first", "context_first"],
    explanation: "天机巨门结合规划与观察防备，提升守护和适应。",
  }),
  tianji_tianliang: createPreferenceBias({
    archetypeScores: { warm_caretaker: 58, protective_keeper: 56 },
    petMatchScores: { gentle_social: 54, alert_guardian: 42 },
    visualScores: { warmth: 58, protection: 58 },
    colorToneHints: ["earth_warm", "wood_green"],
    homeStyleHints: ["warm_care_first", "protected_boundary"],
    gardenStyleHints: ["warm_flower_patch", "protected_shrub_edge"],
    shelterStyleHints: ["soft_canopy", "reinforced_edge"],
    carePriorityHints: ["comfort_first", "safety_first"],
    explanation: "天机天梁结合规划与庇护，提升温暖照护和保护感。",
  }),
  taiyang_taiyin: createPreferenceBias({
    archetypeScores: { adaptive_planner: 66 },
    petMatchScores: { adaptive_partner: 56 },
    visualScores: { warmth: 48, stability: 48, nature: 44 },
    colorToneHints: ["moon_soft", "fire_bright"],
    homeStyleHints: ["adaptive_mixed"],
    gardenStyleHints: ["mixed_natural"],
    shelterStyleHints: ["adaptive_shelter"],
    carePriorityHints: ["context_first"],
    explanation: "太阳太阴形成外放与内敛平衡，提升适应型视觉。",
  }),
  taiyang_jumen: createPreferenceBias({
    archetypeScores: { aesthetic_organizer: 56, protective_keeper: 54 },
    petMatchScores: { curious_playful: 50, alert_guardian: 46 },
    visualScores: { decoration: 58, protection: 52 },
    colorToneHints: ["fire_bright", "wood_green"],
    homeStyleHints: ["flowered_aesthetic", "protected_boundary"],
    gardenStyleHints: ["decorative_garden", "protected_shrub_edge"],
    shelterStyleHints: ["decorated_roof", "reinforced_edge"],
    carePriorityHints: ["beauty_first", "safety_first"],
    explanation: "太阳巨门结合开放表达与观察，提升审美和防备。",
  }),
  taiyang_tianliang: createPreferenceBias({
    archetypeScores: { warm_caretaker: 72 },
    petMatchScores: { gentle_social: 62 },
    visualScores: { warmth: 76, protection: 42 },
    colorToneHints: ["earth_warm", "fire_bright"],
    homeStyleHints: ["warm_care_first"],
    gardenStyleHints: ["warm_flower_patch"],
    shelterStyleHints: ["soft_canopy"],
    carePriorityHints: ["comfort_first"],
    explanation: "太阳天梁结合开放与照护保护，强提升温暖照护。",
  }),
  wuqu_tianfu: createPreferenceBias({
    archetypeScores: { structured_builder: 88 },
    petMatchScores: { stable_attached: 66 },
    visualScores: { order: 90, stability: 72 },
    colorToneHints: ["metal_clear", "earth_warm"],
    homeStyleHints: ["orderly_structured"],
    gardenStyleHints: ["neat_low_grass"],
    shelterStyleHints: ["straight_frame"],
    carePriorityHints: ["storage_first"],
    explanation: "武曲天府结合资源与稳定，强提升秩序建设。",
  }),
  wuqu_tanlang: createPreferenceBias({
    archetypeScores: { aesthetic_organizer: 58, structured_builder: 54 },
    petMatchScores: { curious_playful: 48, stable_attached: 44 },
    visualScores: { decoration: 58, order: 56 },
    colorToneHints: ["fire_bright", "metal_clear"],
    homeStyleHints: ["flowered_aesthetic", "orderly_structured"],
    gardenStyleHints: ["decorative_garden"],
    shelterStyleHints: ["decorated_roof", "straight_frame"],
    carePriorityHints: ["beauty_first", "storage_first"],
    explanation: "武曲贪狼结合资源与审美，提升审美整理和结构感。",
  }),
  wuqu_qisha: createPreferenceBias({
    archetypeScores: { protective_keeper: 78 },
    petMatchScores: { alert_guardian: 66 },
    visualScores: { protection: 84, order: 54 },
    colorToneHints: ["wood_green", "metal_clear"],
    homeStyleHints: ["protected_boundary"],
    gardenStyleHints: ["protected_shrub_edge"],
    shelterStyleHints: ["reinforced_edge"],
    carePriorityHints: ["safety_first"],
    explanation: "武曲七杀结合执行与防御，提升边界守护。",
  }),
  wuqu_pojun: createPreferenceBias({
    archetypeScores: { adaptive_planner: 76 },
    petMatchScores: { adaptive_partner: 62 },
    visualScores: { order: 44, nature: 54, protection: 48 },
    colorToneHints: ["moon_soft", "metal_clear"],
    homeStyleHints: ["adaptive_mixed"],
    gardenStyleHints: ["mixed_natural"],
    shelterStyleHints: ["adaptive_shelter"],
    carePriorityHints: ["context_first"],
    explanation: "武曲破军结合执行与重建，提升适应规划。",
  }),
  tiantong_taiyin: createPreferenceBias({
    archetypeScores: { warm_caretaker: 90 },
    petMatchScores: { gentle_social: 82 },
    visualScores: { warmth: 92, stability: 46 },
    colorToneHints: ["earth_warm", "moon_soft"],
    homeStyleHints: ["warm_care_first"],
    gardenStyleHints: ["warm_flower_patch"],
    shelterStyleHints: ["soft_canopy"],
    carePriorityHints: ["comfort_first"],
    explanation: "天同太阴结合柔和与细腻，强提升温暖照护。",
  }),
  tiantong_jumen: createPreferenceBias({
    archetypeScores: { quiet_maintainer: 70 },
    petMatchScores: { quiet_observer: 64 },
    visualScores: { stability: 66, protection: 44 },
    colorToneHints: ["water_quiet", "moon_soft"],
    homeStyleHints: ["quiet_minimal"],
    gardenStyleHints: ["quiet_shade"],
    shelterStyleHints: ["low_quiet_shelter"],
    carePriorityHints: ["stability_first"],
    explanation: "天同巨门结合舒适与谨慎，提升安静维护。",
  }),
  tiantong_tianliang: createPreferenceBias({
    archetypeScores: { warm_caretaker: 68, protective_keeper: 56 },
    petMatchScores: { gentle_social: 62, alert_guardian: 42 },
    visualScores: { warmth: 68, protection: 58 },
    colorToneHints: ["earth_warm", "wood_green"],
    homeStyleHints: ["warm_care_first", "protected_boundary"],
    gardenStyleHints: ["warm_flower_patch", "protected_shrub_edge"],
    shelterStyleHints: ["soft_canopy", "reinforced_edge"],
    carePriorityHints: ["comfort_first", "safety_first"],
    explanation: "天同天梁结合照护与庇护，提升温暖照护和守护。",
  }),
  lianzhen_tianfu: createPreferenceBias({
    archetypeScores: { structured_builder: 58, protective_keeper: 56 },
    petMatchScores: { stable_attached: 48, alert_guardian: 46 },
    visualScores: { order: 64, protection: 56, stability: 52 },
    colorToneHints: ["metal_clear", "wood_green"],
    homeStyleHints: ["orderly_structured", "protected_boundary"],
    gardenStyleHints: ["neat_low_grass", "protected_shrub_edge"],
    shelterStyleHints: ["straight_frame", "reinforced_edge"],
    carePriorityHints: ["storage_first", "safety_first"],
    explanation: "廉贞天府结合规则与资源，提升结构和保护。",
  }),
  lianzhen_tanlang: createPreferenceBias({
    archetypeScores: { aesthetic_organizer: 88 },
    petMatchScores: { curious_playful: 70 },
    visualScores: { decoration: 92, order: 38 },
    colorToneHints: ["fire_bright"],
    homeStyleHints: ["flowered_aesthetic"],
    gardenStyleHints: ["decorative_garden"],
    shelterStyleHints: ["decorated_roof"],
    carePriorityHints: ["beauty_first"],
    explanation: "廉贞贪狼结合规则与审美，强提升审美整理。",
  }),
  lianzhen_qisha: createPreferenceBias({
    archetypeScores: { protective_keeper: 90 },
    petMatchScores: { alert_guardian: 80 },
    visualScores: { protection: 92, order: 50 },
    colorToneHints: ["wood_green"],
    homeStyleHints: ["protected_boundary"],
    gardenStyleHints: ["protected_shrub_edge"],
    shelterStyleHints: ["reinforced_edge"],
    carePriorityHints: ["safety_first"],
    explanation: "廉贞七杀结合规则与防御，强提升边界守护。",
  }),
  lianzhen_pojun: createPreferenceBias({
    archetypeScores: { adaptive_planner: 66, protective_keeper: 58 },
    petMatchScores: { adaptive_partner: 58, alert_guardian: 48 },
    visualScores: { protection: 58, nature: 54 },
    colorToneHints: ["moon_soft", "wood_green"],
    homeStyleHints: ["adaptive_mixed", "protected_boundary"],
    gardenStyleHints: ["mixed_natural", "protected_shrub_edge"],
    shelterStyleHints: ["adaptive_shelter", "reinforced_edge"],
    carePriorityHints: ["context_first", "safety_first"],
    explanation: "廉贞破军结合规则与重建，提升适应规划和保护。",
  }),
  tianfu_tianxiang: createPreferenceBias({
    archetypeScores: { structured_builder: 62, warm_caretaker: 58 },
    petMatchScores: { stable_attached: 54, gentle_social: 52 },
    visualScores: { order: 66, warmth: 54, stability: 58 },
    colorToneHints: ["metal_clear", "earth_warm"],
    homeStyleHints: ["orderly_structured", "warm_care_first"],
    gardenStyleHints: ["neat_low_grass", "warm_flower_patch"],
    shelterStyleHints: ["straight_frame", "soft_canopy"],
    carePriorityHints: ["storage_first", "comfort_first"],
    explanation: "天府天相结合资源与服务秩序，提升结构化照护。",
  }),
  taiyin_tianliang: createPreferenceBias({
    archetypeScores: { warm_caretaker: 64, quiet_maintainer: 60 },
    petMatchScores: { gentle_social: 60, quiet_observer: 54 },
    visualScores: { warmth: 62, stability: 60, protection: 46 },
    colorToneHints: ["moon_soft", "earth_warm"],
    homeStyleHints: ["warm_care_first", "quiet_minimal"],
    gardenStyleHints: ["warm_flower_patch", "quiet_shade"],
    shelterStyleHints: ["soft_canopy", "low_quiet_shelter"],
    carePriorityHints: ["comfort_first", "stability_first"],
    explanation: "太阴天梁结合细腻与庇护，提升温暖照护和安静维护。",
  }),
  qisha_pojun: createPreferenceBias({
    archetypeScores: { adaptive_planner: 82, protective_keeper: 76 },
    petMatchScores: { adaptive_partner: 70, alert_guardian: 64 },
    visualScores: { protection: 76, nature: 64, order: 38 },
    colorToneHints: ["moon_soft", "wood_green"],
    homeStyleHints: ["adaptive_mixed", "protected_boundary"],
    gardenStyleHints: ["mixed_natural", "protected_shrub_edge"],
    shelterStyleHints: ["adaptive_shelter", "reinforced_edge"],
    carePriorityHints: ["context_first", "safety_first"],
    explanation: "七杀破军结合行动与重建，强提升适应规划和守护。",
  }),
}
