/**
 * 当前文件负责：定义 14 主星的视觉概率偏好。
 */

import type {
  ZiweiMainStar,
  ZiweiPreferenceBias,
} from "./ziwei-probability.types"
import { createPreferenceBias } from "./ziwei-preference-helpers"

export const ziweiStarPreferenceBiases: Record<
  ZiweiMainStar,
  ZiweiPreferenceBias
> = {
  ziwei: createPreferenceBias({
    archetypeScores: { structured_builder: 82, quiet_maintainer: 58 },
    petMatchScores: { stable_attached: 72, quiet_observer: 48 },
    visualScores: { order: 86, stability: 76, protection: 52 },
    colorToneHints: ["metal_clear", "water_quiet"],
    homeStyleHints: ["orderly_structured", "quiet_minimal"],
    gardenStyleHints: ["neat_low_grass"],
    shelterStyleHints: ["straight_frame"],
    carePriorityHints: ["storage_first", "stability_first"],
    explanation: "紫微强调中心感、管理和稳定，倾向结构化家园与稳态陪伴。",
  }),
  tianji: createPreferenceBias({
    archetypeScores: { adaptive_planner: 82, aesthetic_organizer: 50 },
    petMatchScores: { adaptive_partner: 74, curious_playful: 46 },
    visualScores: { nature: 62, decoration: 44, order: 50 },
    colorToneHints: ["moon_soft", "wood_green"],
    homeStyleHints: ["adaptive_mixed"],
    gardenStyleHints: ["mixed_natural"],
    shelterStyleHints: ["adaptive_shelter"],
    carePriorityHints: ["context_first"],
    explanation: "天机强调规划、变化和观察，倾向适应型空间与动态路径。",
  }),
  taiyang: createPreferenceBias({
    archetypeScores: { aesthetic_organizer: 64, warm_caretaker: 62 },
    petMatchScores: { curious_playful: 68, soft_companion: 46 },
    visualScores: { warmth: 70, decoration: 58, nature: 42 },
    colorToneHints: ["fire_bright", "earth_warm"],
    homeStyleHints: ["flowered_aesthetic", "warm_care_first"],
    gardenStyleHints: ["decorative_garden", "warm_flower_patch"],
    shelterStyleHints: ["decorated_roof"],
    carePriorityHints: ["beauty_first", "comfort_first"],
    explanation: "太阳强调开放、照明和积极表达，倾向明亮暖色与开放照护。",
  }),
  wuqu: createPreferenceBias({
    archetypeScores: { structured_builder: 88 },
    petMatchScores: { stable_attached: 64, alert_guardian: 42 },
    visualScores: { order: 88, stability: 72, protection: 46 },
    colorToneHints: ["metal_clear", "earth_warm"],
    homeStyleHints: ["orderly_structured"],
    gardenStyleHints: ["neat_low_grass"],
    shelterStyleHints: ["straight_frame"],
    carePriorityHints: ["storage_first"],
    explanation: "武曲强调资源、执行和效率，倾向地基、储物、路径与清晰结构。",
  }),
  tiantong: createPreferenceBias({
    archetypeScores: { warm_caretaker: 88 },
    petMatchScores: { soft_companion: 84, stable_attached: 48 },
    visualScores: { warmth: 88, stability: 44, decoration: 38 },
    colorToneHints: ["earth_warm", "moon_soft"],
    homeStyleHints: ["warm_care_first"],
    gardenStyleHints: ["warm_flower_patch"],
    shelterStyleHints: ["soft_canopy"],
    carePriorityHints: ["comfort_first"],
    explanation: "天同强调柔和、舒适和亲近，倾向安静生活角、食物角和圆润陪伴。",
  }),
  lianzhen: createPreferenceBias({
    archetypeScores: { protective_keeper: 68, aesthetic_organizer: 62 },
    petMatchScores: { alert_guardian: 62, curious_playful: 42 },
    visualScores: { protection: 70, decoration: 66, order: 58 },
    colorToneHints: ["wood_green", "fire_bright"],
    homeStyleHints: ["protected_boundary", "flowered_aesthetic"],
    gardenStyleHints: ["protected_shrub_edge", "decorative_garden"],
    shelterStyleHints: ["reinforced_edge", "decorated_roof"],
    carePriorityHints: ["safety_first", "beauty_first"],
    explanation: "廉贞强调规则、边界和美感，倾向边界感与整洁装饰并存。",
  }),
  tianfu: createPreferenceBias({
    archetypeScores: { quiet_maintainer: 70, structured_builder: 66 },
    petMatchScores: { stable_attached: 64, quiet_observer: 58 },
    visualScores: { stability: 84, order: 66, warmth: 42 },
    colorToneHints: ["earth_warm", "water_quiet"],
    homeStyleHints: ["quiet_minimal", "orderly_structured"],
    gardenStyleHints: ["quiet_shade", "neat_low_grass"],
    shelterStyleHints: ["low_quiet_shelter", "straight_frame"],
    carePriorityHints: ["stability_first", "storage_first"],
    explanation: "天府强调收藏、资源和庇护，倾向稳定住所与温和储备。",
  }),
  taiyin: createPreferenceBias({
    archetypeScores: { warm_caretaker: 70, quiet_maintainer: 68 },
    petMatchScores: { soft_companion: 68, quiet_observer: 62 },
    visualScores: { warmth: 64, stability: 64, decoration: 40 },
    colorToneHints: ["moon_soft", "water_quiet"],
    homeStyleHints: ["warm_care_first", "quiet_minimal"],
    gardenStyleHints: ["quiet_shade", "warm_flower_patch"],
    shelterStyleHints: ["soft_canopy", "low_quiet_shelter"],
    carePriorityHints: ["comfort_first", "stability_first"],
    explanation: "太阴强调柔和、安静和细腻，倾向月色氛围与安静照护角。",
  }),
  tanlang: createPreferenceBias({
    archetypeScores: { aesthetic_organizer: 86 },
    petMatchScores: { curious_playful: 78, adaptive_partner: 44 },
    visualScores: { decoration: 90, warmth: 54, nature: 58 },
    colorToneHints: ["fire_bright", "earth_warm"],
    homeStyleHints: ["flowered_aesthetic"],
    gardenStyleHints: ["decorative_garden"],
    shelterStyleHints: ["decorated_roof"],
    carePriorityHints: ["beauty_first"],
    explanation: "贪狼强调审美、活力和装饰，倾向花园、色彩与活泼宠物。",
  }),
  jumen: createPreferenceBias({
    archetypeScores: { protective_keeper: 66, quiet_maintainer: 60 },
    petMatchScores: { alert_guardian: 62, quiet_observer: 58 },
    visualScores: { protection: 74, stability: 58, order: 44 },
    colorToneHints: ["water_quiet", "wood_green"],
    homeStyleHints: ["protected_boundary", "quiet_minimal"],
    gardenStyleHints: ["protected_shrub_edge", "quiet_shade"],
    shelterStyleHints: ["reinforced_edge", "low_quiet_shelter"],
    carePriorityHints: ["safety_first", "stability_first"],
    explanation: "巨门强调观察、防备和谨慎表达，倾向观察点与安静边界。",
  }),
  tianxiang: createPreferenceBias({
    archetypeScores: { structured_builder: 64, warm_caretaker: 62 },
    petMatchScores: { stable_attached: 58, soft_companion: 56 },
    visualScores: { order: 70, warmth: 58, stability: 56 },
    colorToneHints: ["metal_clear", "earth_warm"],
    homeStyleHints: ["orderly_structured", "warm_care_first"],
    gardenStyleHints: ["neat_low_grass", "warm_flower_patch"],
    shelterStyleHints: ["straight_frame", "soft_canopy"],
    carePriorityHints: ["storage_first", "comfort_first"],
    explanation: "天相强调协调、服务和礼仪，倾向整洁照护区与服务秩序。",
  }),
  tianliang: createPreferenceBias({
    archetypeScores: { protective_keeper: 70, warm_caretaker: 66 },
    petMatchScores: { soft_companion: 62, alert_guardian: 58 },
    visualScores: { protection: 78, warmth: 66, stability: 62 },
    colorToneHints: ["wood_green", "earth_warm"],
    homeStyleHints: ["protected_boundary", "warm_care_first"],
    gardenStyleHints: ["protected_shrub_edge", "warm_flower_patch"],
    shelterStyleHints: ["reinforced_edge", "soft_canopy"],
    carePriorityHints: ["safety_first", "comfort_first"],
    explanation: "天梁强调保护、照顾和稳定，倾向庇护式照护和守护感。",
  }),
  qisha: createPreferenceBias({
    archetypeScores: { protective_keeper: 82, adaptive_planner: 56 },
    petMatchScores: { alert_guardian: 78, adaptive_partner: 44 },
    visualScores: { protection: 90, order: 50, stability: 46 },
    colorToneHints: ["wood_green", "metal_clear"],
    homeStyleHints: ["protected_boundary", "adaptive_mixed"],
    gardenStyleHints: ["protected_shrub_edge"],
    shelterStyleHints: ["reinforced_edge"],
    carePriorityHints: ["safety_first", "context_first"],
    explanation: "七杀强调行动、防御和边界，倾向加固边界与工具感。",
  }),
  pojun: createPreferenceBias({
    archetypeScores: { adaptive_planner: 84, protective_keeper: 54 },
    petMatchScores: { adaptive_partner: 74, alert_guardian: 46 },
    visualScores: { nature: 58, protection: 54, order: 40 },
    colorToneHints: ["moon_soft", "wood_green"],
    homeStyleHints: ["adaptive_mixed", "protected_boundary"],
    gardenStyleHints: ["mixed_natural"],
    shelterStyleHints: ["adaptive_shelter"],
    carePriorityHints: ["context_first"],
    explanation: "破军强调变化、重建和强行动力，倾向重建路径与适应型住所。",
  }),
}
